<?php

declare(strict_types=1);

/**
 * CreateDamagedTransactional
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Toppy\Sendcloud
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
/**
 * Sendcloud Public REST API
 *
 * Complete Sendcloud API v3 specification - merged from official sendcloud.dev documentation
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: contact@sendcloud.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.18.0
 */
/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
namespace Toppy\Sendcloud\Model;

use \ArrayAccess;
use \Toppy\Sendcloud\ObjectSerializer;

/**
 * CreateDamagedTransactional Class Doc Comment
 *
 * @category Class
 * @package  Toppy\Sendcloud
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class CreateDamagedTransactional implements ModelInterface, ArrayAccess, \JsonSerializable, \Stringable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'CreateDamagedTransactional';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'trackingNumber' => 'string',
        'contentsSalesPrice' => \Toppy\Sendcloud\Model\ContentsSalesValueField::class,
        'contentsPurchasePrice' => \Toppy\Sendcloud\Model\ContentsPurchaseValueField::class,
        'contentsDescription' => 'string',
        'parcelExteriorDescription' => 'string',
        'additionalRemarks' => 'string',
        'customerConfirmation' => \Toppy\Sendcloud\Model\CustomerConfirmationField::class,
        'salesInvoice' => \Toppy\Sendcloud\Model\SalesInvoiceField::class,
        'purchaseInvoice' => \Toppy\Sendcloud\Model\PurchaseInvoiceField::class,
        'exteriorPhoto' => \Toppy\Sendcloud\Model\ExteriorPhotoField::class,
        'interiorPhoto' => \Toppy\Sendcloud\Model\InteriorPhotoField::class,
        'damagePhoto1' => \Toppy\Sendcloud\Model\DamagePhoto1Field::class,
        'damagePhoto2' => \Toppy\Sendcloud\Model\DamagePhoto2Field::class,
        'packagePhoto' => \Toppy\Sendcloud\Model\PackagePhotoField::class,
        'entireProductPhoto' => \Toppy\Sendcloud\Model\EntireProductPhotoField::class
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'trackingNumber' => null,
        'contentsSalesPrice' => null,
        'contentsPurchasePrice' => null,
        'contentsDescription' => null,
        'parcelExteriorDescription' => null,
        'additionalRemarks' => null,
        'customerConfirmation' => null,
        'salesInvoice' => null,
        'purchaseInvoice' => null,
        'exteriorPhoto' => null,
        'interiorPhoto' => null,
        'damagePhoto1' => null,
        'damagePhoto2' => null,
        'packagePhoto' => null,
        'entireProductPhoto' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'trackingNumber' => false,
        'contentsSalesPrice' => false,
        'contentsPurchasePrice' => false,
        'contentsDescription' => false,
        'parcelExteriorDescription' => false,
        'additionalRemarks' => false,
        'customerConfirmation' => false,
        'salesInvoice' => false,
        'purchaseInvoice' => false,
        'exteriorPhoto' => false,
        'interiorPhoto' => false,
        'damagePhoto1' => false,
        'damagePhoto2' => false,
        'packagePhoto' => false,
        'entireProductPhoto' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Checks if a property is nullable
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->openAPINullablesSetToNull, true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'trackingNumber' => 'tracking_number',
        'contentsSalesPrice' => 'contents_sales_price',
        'contentsPurchasePrice' => 'contents_purchase_price',
        'contentsDescription' => 'contents_description',
        'parcelExteriorDescription' => 'parcel_exterior_description',
        'additionalRemarks' => 'additional_remarks',
        'customerConfirmation' => 'customer_confirmation',
        'salesInvoice' => 'sales_invoice',
        'purchaseInvoice' => 'purchase_invoice',
        'exteriorPhoto' => 'exterior_photo',
        'interiorPhoto' => 'interior_photo',
        'damagePhoto1' => 'damage_photo_1',
        'damagePhoto2' => 'damage_photo_2',
        'packagePhoto' => 'package_photo',
        'entireProductPhoto' => 'entire_product_photo'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'trackingNumber' => 'setTrackingNumber',
        'contentsSalesPrice' => 'setContentsSalesPrice',
        'contentsPurchasePrice' => 'setContentsPurchasePrice',
        'contentsDescription' => 'setContentsDescription',
        'parcelExteriorDescription' => 'setParcelExteriorDescription',
        'additionalRemarks' => 'setAdditionalRemarks',
        'customerConfirmation' => 'setCustomerConfirmation',
        'salesInvoice' => 'setSalesInvoice',
        'purchaseInvoice' => 'setPurchaseInvoice',
        'exteriorPhoto' => 'setExteriorPhoto',
        'interiorPhoto' => 'setInteriorPhoto',
        'damagePhoto1' => 'setDamagePhoto1',
        'damagePhoto2' => 'setDamagePhoto2',
        'packagePhoto' => 'setPackagePhoto',
        'entireProductPhoto' => 'setEntireProductPhoto'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'trackingNumber' => 'getTrackingNumber',
        'contentsSalesPrice' => 'getContentsSalesPrice',
        'contentsPurchasePrice' => 'getContentsPurchasePrice',
        'contentsDescription' => 'getContentsDescription',
        'parcelExteriorDescription' => 'getParcelExteriorDescription',
        'additionalRemarks' => 'getAdditionalRemarks',
        'customerConfirmation' => 'getCustomerConfirmation',
        'salesInvoice' => 'getSalesInvoice',
        'purchaseInvoice' => 'getPurchaseInvoice',
        'exteriorPhoto' => 'getExteriorPhoto',
        'interiorPhoto' => 'getInteriorPhoto',
        'damagePhoto1' => 'getDamagePhoto1',
        'damagePhoto2' => 'getDamagePhoto2',
        'packagePhoto' => 'getPackagePhoto',
        'entireProductPhoto' => 'getEntireProductPhoto'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('trackingNumber', $data ?? [], null);
        $this->setIfExists('contentsSalesPrice', $data ?? [], null);
        $this->setIfExists('contentsPurchasePrice', $data ?? [], null);
        $this->setIfExists('contentsDescription', $data ?? [], null);
        $this->setIfExists('parcelExteriorDescription', $data ?? [], null);
        $this->setIfExists('additionalRemarks', $data ?? [], null);
        $this->setIfExists('customerConfirmation', $data ?? [], null);
        $this->setIfExists('salesInvoice', $data ?? [], null);
        $this->setIfExists('purchaseInvoice', $data ?? [], null);
        $this->setIfExists('exteriorPhoto', $data ?? [], null);
        $this->setIfExists('interiorPhoto', $data ?? [], null);
        $this->setIfExists('damagePhoto1', $data ?? [], null);
        $this->setIfExists('damagePhoto2', $data ?? [], null);
        $this->setIfExists('packagePhoto', $data ?? [], null);
        $this->setIfExists('entireProductPhoto', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param mixed  $defaultValue
     * @param array<string, mixed> $fields
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['trackingNumber'] === null) {
            $invalidProperties[] = "'trackingNumber' can't be null";
        }

        if ($this->container['contentsSalesPrice'] === null) {
            $invalidProperties[] = "'contentsSalesPrice' can't be null";
        }

        if ($this->container['contentsDescription'] === null) {
            $invalidProperties[] = "'contentsDescription' can't be null";
        }

        if ($this->container['parcelExteriorDescription'] === null) {
            $invalidProperties[] = "'parcelExteriorDescription' can't be null";
        }

        if ($this->container['additionalRemarks'] === null) {
            $invalidProperties[] = "'additionalRemarks' can't be null";
        }

        if ($this->container['customerConfirmation'] === null) {
            $invalidProperties[] = "'customerConfirmation' can't be null";
        }

        if ($this->container['salesInvoice'] === null) {
            $invalidProperties[] = "'salesInvoice' can't be null";
        }

        if ($this->container['purchaseInvoice'] === null) {
            $invalidProperties[] = "'purchaseInvoice' can't be null";
        }

        if ($this->container['exteriorPhoto'] === null) {
            $invalidProperties[] = "'exteriorPhoto' can't be null";
        }

        if ($this->container['interiorPhoto'] === null) {
            $invalidProperties[] = "'interiorPhoto' can't be null";
        }

        if ($this->container['damagePhoto1'] === null) {
            $invalidProperties[] = "'damagePhoto1' can't be null";
        }

        if ($this->container['damagePhoto2'] === null) {
            $invalidProperties[] = "'damagePhoto2' can't be null";
        }

        if ($this->container['packagePhoto'] === null) {
            $invalidProperties[] = "'packagePhoto' can't be null";
        }

        if ($this->container['entireProductPhoto'] === null) {
            $invalidProperties[] = "'entireProductPhoto' can't be null";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets trackingNumber
     *
     * @return string
     */
    public function getTrackingNumber()
    {
        return $this->container['trackingNumber'];
    }

    /**
     * Sets trackingNumber
     *
     * @param string $trackingNumber Parcel tracking number
     *
     * @return self
     */
    public function setTrackingNumber($trackingNumber)
    {
        if (is_null($trackingNumber)) {
            throw new \InvalidArgumentException('non-nullable trackingNumber cannot be null');
        }

        $this->container['trackingNumber'] = $trackingNumber;

        return $this;
    }

    /**
     * Gets contentsSalesPrice
     *
     * @return \Toppy\Sendcloud\Model\ContentsSalesValueField
     */
    public function getContentsSalesPrice()
    {
        return $this->container['contentsSalesPrice'];
    }

    /**
     * Sets contentsSalesPrice
     *
     * @param \Toppy\Sendcloud\Model\ContentsSalesValueField $contentsSalesPrice contentsSalesPrice
     *
     * @return self
     */
    public function setContentsSalesPrice($contentsSalesPrice)
    {
        if (is_null($contentsSalesPrice)) {
            throw new \InvalidArgumentException('non-nullable contentsSalesPrice cannot be null');
        }

        $this->container['contentsSalesPrice'] = $contentsSalesPrice;

        return $this;
    }

    /**
     * Gets contentsPurchasePrice
     *
     * @return \Toppy\Sendcloud\Model\ContentsPurchaseValueField|null
     */
    public function getContentsPurchasePrice()
    {
        return $this->container['contentsPurchasePrice'];
    }

    /**
     * Sets contentsPurchasePrice
     *
     * @param \Toppy\Sendcloud\Model\ContentsPurchaseValueField|null $contentsPurchasePrice contentsPurchasePrice
     *
     * @return self
     */
    public function setContentsPurchasePrice($contentsPurchasePrice)
    {
        if (is_null($contentsPurchasePrice)) {
            throw new \InvalidArgumentException('non-nullable contentsPurchasePrice cannot be null');
        }

        $this->container['contentsPurchasePrice'] = $contentsPurchasePrice;

        return $this;
    }

    /**
     * Gets contentsDescription
     *
     * @return string
     */
    public function getContentsDescription()
    {
        return $this->container['contentsDescription'];
    }

    /**
     * Sets contentsDescription
     *
     * @param string $contentsDescription Description of the contents of the parcel
     *
     * @return self
     */
    public function setContentsDescription($contentsDescription)
    {
        if (is_null($contentsDescription)) {
            throw new \InvalidArgumentException('non-nullable contentsDescription cannot be null');
        }

        $this->container['contentsDescription'] = $contentsDescription;

        return $this;
    }

    /**
     * Gets parcelExteriorDescription
     *
     * @return string
     */
    public function getParcelExteriorDescription()
    {
        return $this->container['parcelExteriorDescription'];
    }

    /**
     * Sets parcelExteriorDescription
     *
     * @param string $parcelExteriorDescription Parcel exterior description
     *
     * @return self
     */
    public function setParcelExteriorDescription($parcelExteriorDescription)
    {
        if (is_null($parcelExteriorDescription)) {
            throw new \InvalidArgumentException('non-nullable parcelExteriorDescription cannot be null');
        }

        $this->container['parcelExteriorDescription'] = $parcelExteriorDescription;

        return $this;
    }

    /**
     * Gets additionalRemarks
     *
     * @return string
     */
    public function getAdditionalRemarks()
    {
        return $this->container['additionalRemarks'];
    }

    /**
     * Sets additionalRemarks
     *
     * @param string $additionalRemarks Additional remarks about the parcel
     *
     * @return self
     */
    public function setAdditionalRemarks($additionalRemarks)
    {
        if (is_null($additionalRemarks)) {
            throw new \InvalidArgumentException('non-nullable additionalRemarks cannot be null');
        }

        $this->container['additionalRemarks'] = $additionalRemarks;

        return $this;
    }

    /**
     * Gets customerConfirmation
     *
     * @return \Toppy\Sendcloud\Model\CustomerConfirmationField
     */
    public function getCustomerConfirmation()
    {
        return $this->container['customerConfirmation'];
    }

    /**
     * Sets customerConfirmation
     *
     * @param \Toppy\Sendcloud\Model\CustomerConfirmationField $customerConfirmation customerConfirmation
     *
     * @return self
     */
    public function setCustomerConfirmation($customerConfirmation)
    {
        if (is_null($customerConfirmation)) {
            throw new \InvalidArgumentException('non-nullable customerConfirmation cannot be null');
        }

        $this->container['customerConfirmation'] = $customerConfirmation;

        return $this;
    }

    /**
     * Gets salesInvoice
     *
     * @return \Toppy\Sendcloud\Model\SalesInvoiceField
     */
    public function getSalesInvoice()
    {
        return $this->container['salesInvoice'];
    }

    /**
     * Sets salesInvoice
     *
     * @param \Toppy\Sendcloud\Model\SalesInvoiceField $salesInvoice salesInvoice
     *
     * @return self
     */
    public function setSalesInvoice($salesInvoice)
    {
        if (is_null($salesInvoice)) {
            throw new \InvalidArgumentException('non-nullable salesInvoice cannot be null');
        }

        $this->container['salesInvoice'] = $salesInvoice;

        return $this;
    }

    /**
     * Gets purchaseInvoice
     *
     * @return \Toppy\Sendcloud\Model\PurchaseInvoiceField
     */
    public function getPurchaseInvoice()
    {
        return $this->container['purchaseInvoice'];
    }

    /**
     * Sets purchaseInvoice
     *
     * @param \Toppy\Sendcloud\Model\PurchaseInvoiceField $purchaseInvoice purchaseInvoice
     *
     * @return self
     */
    public function setPurchaseInvoice($purchaseInvoice)
    {
        if (is_null($purchaseInvoice)) {
            throw new \InvalidArgumentException('non-nullable purchaseInvoice cannot be null');
        }

        $this->container['purchaseInvoice'] = $purchaseInvoice;

        return $this;
    }

    /**
     * Gets exteriorPhoto
     *
     * @return \Toppy\Sendcloud\Model\ExteriorPhotoField
     */
    public function getExteriorPhoto()
    {
        return $this->container['exteriorPhoto'];
    }

    /**
     * Sets exteriorPhoto
     *
     * @param \Toppy\Sendcloud\Model\ExteriorPhotoField $exteriorPhoto exteriorPhoto
     *
     * @return self
     */
    public function setExteriorPhoto($exteriorPhoto)
    {
        if (is_null($exteriorPhoto)) {
            throw new \InvalidArgumentException('non-nullable exteriorPhoto cannot be null');
        }

        $this->container['exteriorPhoto'] = $exteriorPhoto;

        return $this;
    }

    /**
     * Gets interiorPhoto
     *
     * @return \Toppy\Sendcloud\Model\InteriorPhotoField
     */
    public function getInteriorPhoto()
    {
        return $this->container['interiorPhoto'];
    }

    /**
     * Sets interiorPhoto
     *
     * @param \Toppy\Sendcloud\Model\InteriorPhotoField $interiorPhoto interiorPhoto
     *
     * @return self
     */
    public function setInteriorPhoto($interiorPhoto)
    {
        if (is_null($interiorPhoto)) {
            throw new \InvalidArgumentException('non-nullable interiorPhoto cannot be null');
        }

        $this->container['interiorPhoto'] = $interiorPhoto;

        return $this;
    }

    /**
     * Gets damagePhoto1
     *
     * @return \Toppy\Sendcloud\Model\DamagePhoto1Field
     */
    public function getDamagePhoto1()
    {
        return $this->container['damagePhoto1'];
    }

    /**
     * Sets damagePhoto1
     *
     * @param \Toppy\Sendcloud\Model\DamagePhoto1Field $damagePhoto1 damagePhoto1
     *
     * @return self
     */
    public function setDamagePhoto1($damagePhoto1)
    {
        if (is_null($damagePhoto1)) {
            throw new \InvalidArgumentException('non-nullable damagePhoto1 cannot be null');
        }

        $this->container['damagePhoto1'] = $damagePhoto1;

        return $this;
    }

    /**
     * Gets damagePhoto2
     *
     * @return \Toppy\Sendcloud\Model\DamagePhoto2Field
     */
    public function getDamagePhoto2()
    {
        return $this->container['damagePhoto2'];
    }

    /**
     * Sets damagePhoto2
     *
     * @param \Toppy\Sendcloud\Model\DamagePhoto2Field $damagePhoto2 damagePhoto2
     *
     * @return self
     */
    public function setDamagePhoto2($damagePhoto2)
    {
        if (is_null($damagePhoto2)) {
            throw new \InvalidArgumentException('non-nullable damagePhoto2 cannot be null');
        }

        $this->container['damagePhoto2'] = $damagePhoto2;

        return $this;
    }

    /**
     * Gets packagePhoto
     *
     * @return \Toppy\Sendcloud\Model\PackagePhotoField
     */
    public function getPackagePhoto()
    {
        return $this->container['packagePhoto'];
    }

    /**
     * Sets packagePhoto
     *
     * @param \Toppy\Sendcloud\Model\PackagePhotoField $packagePhoto packagePhoto
     *
     * @return self
     */
    public function setPackagePhoto($packagePhoto)
    {
        if (is_null($packagePhoto)) {
            throw new \InvalidArgumentException('non-nullable packagePhoto cannot be null');
        }

        $this->container['packagePhoto'] = $packagePhoto;

        return $this;
    }

    /**
     * Gets entireProductPhoto
     *
     * @return \Toppy\Sendcloud\Model\EntireProductPhotoField
     */
    public function getEntireProductPhoto()
    {
        return $this->container['entireProductPhoto'];
    }

    /**
     * Sets entireProductPhoto
     *
     * @param \Toppy\Sendcloud\Model\EntireProductPhotoField $entireProductPhoto entireProductPhoto
     *
     * @return self
     */
    public function setEntireProductPhoto($entireProductPhoto)
    {
        if (is_null($entireProductPhoto)) {
            throw new \InvalidArgumentException('non-nullable entireProductPhoto cannot be null');
        }

        $this->container['entireProductPhoto'] = $entireProductPhoto;

        return $this;
    }

    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     */
    public function __toString(): string
    {
        return (string) json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
