<?php

declare(strict_types=1);

/**
 * CreateLabelsAsyncAllOfOrders
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Toppy\Sendcloud
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
/**
 * Sendcloud Public REST API
 *
 * Complete Sendcloud API v3 specification - merged from official Stoplight documentation bundles
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: contact@sendcloud.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.18.0
 */
/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
namespace Toppy\Sendcloud\Model;

use \ArrayAccess;
use \Toppy\Sendcloud\ObjectSerializer;

/**
 * CreateLabelsAsyncAllOfOrders Class Doc Comment
 *
 * @category Class
 * @package  Toppy\Sendcloud
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class CreateLabelsAsyncAllOfOrders implements ModelInterface, ArrayAccess, \JsonSerializable, \Stringable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'create_labels_async_allOf_orders';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'parcels' => '\Toppy\Sendcloud\Model\CreateLabelParcel[]',
        'orderId' => 'string',
        'orderNumber' => 'string',
        'applyShippingRules' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'parcels' => null,
        'orderId' => null,
        'orderNumber' => null,
        'applyShippingRules' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'parcels' => false,
        'orderId' => false,
        'orderNumber' => false,
        'applyShippingRules' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Checks if a property is nullable
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->openAPINullablesSetToNull, true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'parcels' => 'parcels',
        'orderId' => 'order_id',
        'orderNumber' => 'order_number',
        'applyShippingRules' => 'apply_shipping_rules'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'parcels' => 'setParcels',
        'orderId' => 'setOrderId',
        'orderNumber' => 'setOrderNumber',
        'applyShippingRules' => 'setApplyShippingRules'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'parcels' => 'getParcels',
        'orderId' => 'getOrderId',
        'orderNumber' => 'getOrderNumber',
        'applyShippingRules' => 'getApplyShippingRules'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('parcels', $data ?? [], null);
        $this->setIfExists('orderId', $data ?? [], null);
        $this->setIfExists('orderNumber', $data ?? [], null);
        $this->setIfExists('applyShippingRules', $data ?? [], false);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param mixed  $defaultValue
     * @param array<string, mixed> $fields
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (!is_null($this->container['parcels']) && (count($this->container['parcels']) > 50)) {
            $invalidProperties[] = "invalid value for 'parcels', number of items must be less than or equal to 50.";
        }

        if (!is_null($this->container['parcels']) && (count($this->container['parcels']) < 1)) {
            $invalidProperties[] = "invalid value for 'parcels', number of items must be greater than or equal to 1.";
        }

        if ($this->container['orderId'] === null) {
            $invalidProperties[] = "'orderId' can't be null";
        }

        if ((mb_strlen((string) $this->container['orderId']) > 64)) {
            $invalidProperties[] = "invalid value for 'orderId', the character length must be smaller than or equal to 64.";
        }

        if ((mb_strlen((string) $this->container['orderId']) < 1)) {
            $invalidProperties[] = "invalid value for 'orderId', the character length must be bigger than or equal to 1.";
        }

        if ($this->container['orderNumber'] === null) {
            $invalidProperties[] = "'orderNumber' can't be null";
        }

        if ((mb_strlen((string) $this->container['orderNumber']) > 255)) {
            $invalidProperties[] = "invalid value for 'orderNumber', the character length must be smaller than or equal to 255.";
        }

        if ((mb_strlen((string) $this->container['orderNumber']) < 1)) {
            $invalidProperties[] = "invalid value for 'orderNumber', the character length must be bigger than or equal to 1.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets parcels
     *
     * @return \Toppy\Sendcloud\Model\CreateLabelParcel[]|null
     */
    public function getParcels()
    {
        return $this->container['parcels'];
    }

    /**
     * Sets parcels
     *
     * @param \Toppy\Sendcloud\Model\CreateLabelParcel[]|null $parcels Represent each package of the shipment. Each carrier can have its own number of parcels limit per shipment, otherwise there is a restriction to a maximum of 50 parcels (default). If left empty one parcel will be created from an entire order.
     *
     * @return self
     */
    public function setParcels($parcels)
    {
        if (is_null($parcels)) {
            throw new \InvalidArgumentException('non-nullable parcels cannot be null');
        }

        if ((count($parcels) > 50)) {
            throw new \InvalidArgumentException('invalid value for $parcels when calling CreateLabelsAsyncAllOfOrders., number of items must be less than or equal to 50.');
        }

        if ((count($parcels) < 1)) {
            throw new \InvalidArgumentException('invalid length for $parcels when calling CreateLabelsAsyncAllOfOrders., number of items must be greater than or equal to 1.');
        }

        $this->container['parcels'] = $parcels;

        return $this;
    }

    /**
     * Gets orderId
     *
     * @return string
     */
    public function getOrderId()
    {
        return $this->container['orderId'];
    }

    /**
     * Sets orderId
     *
     * @param string $orderId External order ID assigned by shop system. Used to identify an order to be shipped.
     *
     * @return self
     */
    public function setOrderId($orderId)
    {
        if (is_null($orderId)) {
            throw new \InvalidArgumentException('non-nullable orderId cannot be null');
        }

        if ((mb_strlen($orderId) > 64)) {
            throw new \InvalidArgumentException('invalid length for $orderId when calling CreateLabelsAsyncAllOfOrders., must be smaller than or equal to 64.');
        }

        if ((mb_strlen($orderId) < 1)) {
            throw new \InvalidArgumentException('invalid length for $orderId when calling CreateLabelsAsyncAllOfOrders., must be bigger than or equal to 1.');
        }

        $this->container['orderId'] = $orderId;

        return $this;
    }

    /**
     * Gets orderNumber
     *
     * @return string
     */
    public function getOrderNumber()
    {
        return $this->container['orderNumber'];
    }

    /**
     * Sets orderNumber
     *
     * @param string $orderNumber An identification of an order in a shop system (often unique). Used to identify an order to be shipped.
     *
     * @return self
     */
    public function setOrderNumber($orderNumber)
    {
        if (is_null($orderNumber)) {
            throw new \InvalidArgumentException('non-nullable orderNumber cannot be null');
        }

        if ((mb_strlen($orderNumber) > 255)) {
            throw new \InvalidArgumentException('invalid length for $orderNumber when calling CreateLabelsAsyncAllOfOrders., must be smaller than or equal to 255.');
        }

        if ((mb_strlen($orderNumber) < 1)) {
            throw new \InvalidArgumentException('invalid length for $orderNumber when calling CreateLabelsAsyncAllOfOrders., must be bigger than or equal to 1.');
        }

        $this->container['orderNumber'] = $orderNumber;

        return $this;
    }

    /**
     * Gets applyShippingRules
     *
     * @return bool|null
     */
    public function getApplyShippingRules()
    {
        return $this->container['applyShippingRules'];
    }

    /**
     * Sets applyShippingRules
     *
     * @param bool|null $applyShippingRules Apply shipping rules for this order.
     *
     * @return self
     */
    public function setApplyShippingRules($applyShippingRules)
    {
        if (is_null($applyShippingRules)) {
            throw new \InvalidArgumentException('non-nullable applyShippingRules cannot be null');
        }

        $this->container['applyShippingRules'] = $applyShippingRules;

        return $this;
    }

    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     */
    public function __toString(): string
    {
        return (string) json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
