<?php

declare(strict_types=1);

/**
 * DeliveryOption
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Toppy\Sendcloud
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
/**
 * Sendcloud Public REST API
 *
 * Complete Sendcloud API v3 specification - merged from official sendcloud.dev documentation
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: contact@sendcloud.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.18.0
 */
/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
namespace Toppy\Sendcloud\Model;
use \Toppy\Sendcloud\ObjectSerializer;

/**
 * DeliveryOption Class Doc Comment
 *
 * @category Class
 * @description The options the customer has for returning this parcel:  - &#x60;drop_off_point&#x60;: At a drop-off point - Print at home - &#x60;drop_off_labelless&#x60;: At a drop-off point - No printer needed - &#x60;in_store&#x60;: Return in store - &#x60;pickup&#x60;: Arrange a pick-up
 * @package  Toppy\Sendcloud
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DeliveryOption
{
    /**
     * Possible values of this enum
     */
    public const DROP_OFF_POINT = 'drop_off_point';

    public const DROP_OFF_LABELLESS = 'drop_off_labelless';

    public const PICKUP = 'pickup';

    public const IN_STORE = 'in_store';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::DROP_OFF_POINT,
            self::DROP_OFF_LABELLESS,
            self::PICKUP,
            self::IN_STORE
        ];
    }
}
