<?php
/**
 * ModelReturn
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Toppy\Sendcloud
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Sendcloud Public REST API
 *
 * Complete Sendcloud API v3 specification - merged from official Stoplight documentation bundles
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: contact@sendcloud.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.18.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Toppy\Sendcloud\Model;

use \ArrayAccess;
use \Toppy\Sendcloud\ObjectSerializer;

/**
 * ModelReturn Class Doc Comment
 *
 * @category Class
 * @description A Sendcloud return object
 * @package  Toppy\Sendcloud
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ModelReturn implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Return';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'fromAddress' => '\Toppy\Sendcloud\Model\AddressWithRequiredFields',
        'toAddress' => '\Toppy\Sendcloud\Model\AddressWithRequiredFields',
        'shippingProduct' => '\Toppy\Sendcloud\Model\ShippingProductsRef',
        'dimensions' => '\Toppy\Sendcloud\Model\Dimension',
        'weight' => '\Toppy\Sendcloud\Model\Weight',
        'colloCount' => 'int',
        'parcelItems' => '\Toppy\Sendcloud\Model\ParcelItemReturnsDetails[]',
        'sendTrackingEmails' => 'bool',
        'brandId' => 'int',
        'labelUrl' => 'string',
        'label' => '\Toppy\Sendcloud\Model\ReturnLabel',
        'labelCost' => '\Toppy\Sendcloud\Model\Price',
        'insurance' => 'bool',
        'trackingNumber' => 'string',
        'trackingUrl' => 'string',
        'isCancellable' => 'bool',
        'statusHistory' => '\Toppy\Sendcloud\Model\DetailedTrackingBlobStatus[]',
        'createdAt' => '\DateTime',
        'deliveredAt' => 'float',
        'deliveredAtIso' => '\DateTime',
        'reason' => '\Toppy\Sendcloud\Model\ReturnReason',
        'refund' => '\Toppy\Sendcloud\Model\ReturnRefund',
        'returnFee' => '\Toppy\Sendcloud\Model\PriceWithAnyCurrency',
        'orderNumber' => 'string',
        'contract' => 'int',
        'customsInvoiceNr' => 'string',
        'customsShipmentType' => 'int',
        'deliveryOption' => '\Toppy\Sendcloud\Model\DeliveryOption',
        'images' => '\Toppy\Sendcloud\Model\ReturnImagesInner[]',
        'status' => 'string',
        'customsInformation' => '\Toppy\Sendcloud\Model\ParcelCustomsInformation',
        'errors' => '\Toppy\Sendcloud\Model\ErrorObject[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'fromAddress' => null,
        'toAddress' => null,
        'shippingProduct' => null,
        'dimensions' => null,
        'weight' => null,
        'colloCount' => null,
        'parcelItems' => null,
        'sendTrackingEmails' => null,
        'brandId' => null,
        'labelUrl' => null,
        'label' => null,
        'labelCost' => null,
        'insurance' => null,
        'trackingNumber' => null,
        'trackingUrl' => null,
        'isCancellable' => null,
        'statusHistory' => null,
        'createdAt' => 'date-time',
        'deliveredAt' => null,
        'deliveredAtIso' => 'date-time',
        'reason' => null,
        'refund' => null,
        'returnFee' => null,
        'orderNumber' => null,
        'contract' => null,
        'customsInvoiceNr' => null,
        'customsShipmentType' => null,
        'deliveryOption' => null,
        'images' => null,
        'status' => null,
        'customsInformation' => null,
        'errors' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'fromAddress' => false,
        'toAddress' => false,
        'shippingProduct' => false,
        'dimensions' => false,
        'weight' => false,
        'colloCount' => false,
        'parcelItems' => false,
        'sendTrackingEmails' => false,
        'brandId' => false,
        'labelUrl' => false,
        'label' => false,
        'labelCost' => false,
        'insurance' => false,
        'trackingNumber' => false,
        'trackingUrl' => false,
        'isCancellable' => false,
        'statusHistory' => false,
        'createdAt' => false,
        'deliveredAt' => false,
        'deliveredAtIso' => false,
        'reason' => false,
        'refund' => false,
        'returnFee' => false,
        'orderNumber' => false,
        'contract' => false,
        'customsInvoiceNr' => false,
        'customsShipmentType' => false,
        'deliveryOption' => false,
        'images' => false,
        'status' => false,
        'customsInformation' => false,
        'errors' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'fromAddress' => 'from_address',
        'toAddress' => 'to_address',
        'shippingProduct' => 'shipping_product',
        'dimensions' => 'dimensions',
        'weight' => 'weight',
        'colloCount' => 'collo_count',
        'parcelItems' => 'parcel_items',
        'sendTrackingEmails' => 'send_tracking_emails',
        'brandId' => 'brand_id',
        'labelUrl' => 'label_url',
        'label' => 'label',
        'labelCost' => 'label_cost',
        'insurance' => 'insurance',
        'trackingNumber' => 'tracking_number',
        'trackingUrl' => 'tracking_url',
        'isCancellable' => 'is_cancellable',
        'statusHistory' => 'status_history',
        'createdAt' => 'created_at',
        'deliveredAt' => 'delivered_at',
        'deliveredAtIso' => 'delivered_at_iso',
        'reason' => 'reason',
        'refund' => 'refund',
        'returnFee' => 'return_fee',
        'orderNumber' => 'order_number',
        'contract' => 'contract',
        'customsInvoiceNr' => 'customs_invoice_nr',
        'customsShipmentType' => 'customs_shipment_type',
        'deliveryOption' => 'delivery_option',
        'images' => 'images',
        'status' => 'status',
        'customsInformation' => 'customs_information',
        'errors' => 'errors'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'fromAddress' => 'setFromAddress',
        'toAddress' => 'setToAddress',
        'shippingProduct' => 'setShippingProduct',
        'dimensions' => 'setDimensions',
        'weight' => 'setWeight',
        'colloCount' => 'setColloCount',
        'parcelItems' => 'setParcelItems',
        'sendTrackingEmails' => 'setSendTrackingEmails',
        'brandId' => 'setBrandId',
        'labelUrl' => 'setLabelUrl',
        'label' => 'setLabel',
        'labelCost' => 'setLabelCost',
        'insurance' => 'setInsurance',
        'trackingNumber' => 'setTrackingNumber',
        'trackingUrl' => 'setTrackingUrl',
        'isCancellable' => 'setIsCancellable',
        'statusHistory' => 'setStatusHistory',
        'createdAt' => 'setCreatedAt',
        'deliveredAt' => 'setDeliveredAt',
        'deliveredAtIso' => 'setDeliveredAtIso',
        'reason' => 'setReason',
        'refund' => 'setRefund',
        'returnFee' => 'setReturnFee',
        'orderNumber' => 'setOrderNumber',
        'contract' => 'setContract',
        'customsInvoiceNr' => 'setCustomsInvoiceNr',
        'customsShipmentType' => 'setCustomsShipmentType',
        'deliveryOption' => 'setDeliveryOption',
        'images' => 'setImages',
        'status' => 'setStatus',
        'customsInformation' => 'setCustomsInformation',
        'errors' => 'setErrors'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'fromAddress' => 'getFromAddress',
        'toAddress' => 'getToAddress',
        'shippingProduct' => 'getShippingProduct',
        'dimensions' => 'getDimensions',
        'weight' => 'getWeight',
        'colloCount' => 'getColloCount',
        'parcelItems' => 'getParcelItems',
        'sendTrackingEmails' => 'getSendTrackingEmails',
        'brandId' => 'getBrandId',
        'labelUrl' => 'getLabelUrl',
        'label' => 'getLabel',
        'labelCost' => 'getLabelCost',
        'insurance' => 'getInsurance',
        'trackingNumber' => 'getTrackingNumber',
        'trackingUrl' => 'getTrackingUrl',
        'isCancellable' => 'getIsCancellable',
        'statusHistory' => 'getStatusHistory',
        'createdAt' => 'getCreatedAt',
        'deliveredAt' => 'getDeliveredAt',
        'deliveredAtIso' => 'getDeliveredAtIso',
        'reason' => 'getReason',
        'refund' => 'getRefund',
        'returnFee' => 'getReturnFee',
        'orderNumber' => 'getOrderNumber',
        'contract' => 'getContract',
        'customsInvoiceNr' => 'getCustomsInvoiceNr',
        'customsShipmentType' => 'getCustomsShipmentType',
        'deliveryOption' => 'getDeliveryOption',
        'images' => 'getImages',
        'status' => 'getStatus',
        'customsInformation' => 'getCustomsInformation',
        'errors' => 'getErrors'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const CUSTOMS_SHIPMENT_TYPE_NUMBER_0 = 0;
    public const CUSTOMS_SHIPMENT_TYPE_NUMBER_1 = 1;
    public const CUSTOMS_SHIPMENT_TYPE_NUMBER_2 = 2;
    public const CUSTOMS_SHIPMENT_TYPE_NUMBER_3 = 3;
    public const CUSTOMS_SHIPMENT_TYPE_NUMBER_4 = 4;
    public const STATUS_OPEN = 'open';
    public const STATUS_REQUESTED = 'requested';
    public const STATUS_REQUEST_REJECTED = 'request_rejected';
    public const STATUS_AWAITING_PAYMENT = 'awaiting_payment';
    public const STATUS_PAYMENT_FAILED = 'payment_failed';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getCustomsShipmentTypeAllowableValues()
    {
        return [
            self::CUSTOMS_SHIPMENT_TYPE_NUMBER_0,
            self::CUSTOMS_SHIPMENT_TYPE_NUMBER_1,
            self::CUSTOMS_SHIPMENT_TYPE_NUMBER_2,
            self::CUSTOMS_SHIPMENT_TYPE_NUMBER_3,
            self::CUSTOMS_SHIPMENT_TYPE_NUMBER_4,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getStatusAllowableValues()
    {
        return [
            self::STATUS_OPEN,
            self::STATUS_REQUESTED,
            self::STATUS_REQUEST_REJECTED,
            self::STATUS_AWAITING_PAYMENT,
            self::STATUS_PAYMENT_FAILED,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('fromAddress', $data ?? [], null);
        $this->setIfExists('toAddress', $data ?? [], null);
        $this->setIfExists('shippingProduct', $data ?? [], null);
        $this->setIfExists('dimensions', $data ?? [], null);
        $this->setIfExists('weight', $data ?? [], null);
        $this->setIfExists('colloCount', $data ?? [], 1);
        $this->setIfExists('parcelItems', $data ?? [], null);
        $this->setIfExists('sendTrackingEmails', $data ?? [], false);
        $this->setIfExists('brandId', $data ?? [], null);
        $this->setIfExists('labelUrl', $data ?? [], null);
        $this->setIfExists('label', $data ?? [], null);
        $this->setIfExists('labelCost', $data ?? [], null);
        $this->setIfExists('insurance', $data ?? [], null);
        $this->setIfExists('trackingNumber', $data ?? [], null);
        $this->setIfExists('trackingUrl', $data ?? [], null);
        $this->setIfExists('isCancellable', $data ?? [], null);
        $this->setIfExists('statusHistory', $data ?? [], null);
        $this->setIfExists('createdAt', $data ?? [], null);
        $this->setIfExists('deliveredAt', $data ?? [], null);
        $this->setIfExists('deliveredAtIso', $data ?? [], null);
        $this->setIfExists('reason', $data ?? [], null);
        $this->setIfExists('refund', $data ?? [], null);
        $this->setIfExists('returnFee', $data ?? [], null);
        $this->setIfExists('orderNumber', $data ?? [], null);
        $this->setIfExists('contract', $data ?? [], null);
        $this->setIfExists('customsInvoiceNr', $data ?? [], null);
        $this->setIfExists('customsShipmentType', $data ?? [], null);
        $this->setIfExists('deliveryOption', $data ?? [], null);
        $this->setIfExists('images', $data ?? [], null);
        $this->setIfExists('status', $data ?? [], null);
        $this->setIfExists('customsInformation', $data ?? [], null);
        $this->setIfExists('errors', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['fromAddress'] === null) {
            $invalidProperties[] = "'fromAddress' can't be null";
        }
        if ($this->container['toAddress'] === null) {
            $invalidProperties[] = "'toAddress' can't be null";
        }
        if ($this->container['shippingProduct'] === null) {
            $invalidProperties[] = "'shippingProduct' can't be null";
        }
        if ($this->container['weight'] === null) {
            $invalidProperties[] = "'weight' can't be null";
        }
        if (!is_null($this->container['colloCount']) && ($this->container['colloCount'] < 1)) {
            $invalidProperties[] = "invalid value for 'colloCount', must be bigger than or equal to 1.";
        }

        if ($this->container['sendTrackingEmails'] === null) {
            $invalidProperties[] = "'sendTrackingEmails' can't be null";
        }
        if (!is_null($this->container['brandId']) && ($this->container['brandId'] < 1)) {
            $invalidProperties[] = "invalid value for 'brandId', must be bigger than or equal to 1.";
        }

        if ($this->container['isCancellable'] === null) {
            $invalidProperties[] = "'isCancellable' can't be null";
        }
        if ($this->container['statusHistory'] === null) {
            $invalidProperties[] = "'statusHistory' can't be null";
        }
        if ((count($this->container['statusHistory']) < 1)) {
            $invalidProperties[] = "invalid value for 'statusHistory', number of items must be greater than or equal to 1.";
        }

        if ($this->container['createdAt'] === null) {
            $invalidProperties[] = "'createdAt' can't be null";
        }
        $allowedValues = $this->getCustomsShipmentTypeAllowableValues();
        if (!is_null($this->container['customsShipmentType']) && !in_array($this->container['customsShipmentType'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'customsShipmentType', must be one of '%s'",
                $this->container['customsShipmentType'],
                implode("', '", $allowedValues)
            );
        }

        if (!is_null($this->container['images']) && (count($this->container['images']) > 10)) {
            $invalidProperties[] = "invalid value for 'images', number of items must be less than or equal to 10.";
        }

        $allowedValues = $this->getStatusAllowableValues();
        if (!is_null($this->container['status']) && !in_array($this->container['status'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'status', must be one of '%s'",
                $this->container['status'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets fromAddress
     *
     * @return \Toppy\Sendcloud\Model\AddressWithRequiredFields
     */
    public function getFromAddress()
    {
        return $this->container['fromAddress'];
    }

    /**
     * Sets fromAddress
     *
     * @param \Toppy\Sendcloud\Model\AddressWithRequiredFields $fromAddress fromAddress
     *
     * @return self
     */
    public function setFromAddress($fromAddress)
    {
        if (is_null($fromAddress)) {
            throw new \InvalidArgumentException('non-nullable fromAddress cannot be null');
        }
        $this->container['fromAddress'] = $fromAddress;

        return $this;
    }

    /**
     * Gets toAddress
     *
     * @return \Toppy\Sendcloud\Model\AddressWithRequiredFields
     */
    public function getToAddress()
    {
        return $this->container['toAddress'];
    }

    /**
     * Sets toAddress
     *
     * @param \Toppy\Sendcloud\Model\AddressWithRequiredFields $toAddress toAddress
     *
     * @return self
     */
    public function setToAddress($toAddress)
    {
        if (is_null($toAddress)) {
            throw new \InvalidArgumentException('non-nullable toAddress cannot be null');
        }
        $this->container['toAddress'] = $toAddress;

        return $this;
    }

    /**
     * Gets shippingProduct
     *
     * @return \Toppy\Sendcloud\Model\ShippingProductsRef
     */
    public function getShippingProduct()
    {
        return $this->container['shippingProduct'];
    }

    /**
     * Sets shippingProduct
     *
     * @param \Toppy\Sendcloud\Model\ShippingProductsRef $shippingProduct shippingProduct
     *
     * @return self
     */
    public function setShippingProduct($shippingProduct)
    {
        if (is_null($shippingProduct)) {
            throw new \InvalidArgumentException('non-nullable shippingProduct cannot be null');
        }
        $this->container['shippingProduct'] = $shippingProduct;

        return $this;
    }

    /**
     * Gets dimensions
     *
     * @return \Toppy\Sendcloud\Model\Dimension|null
     */
    public function getDimensions()
    {
        return $this->container['dimensions'];
    }

    /**
     * Sets dimensions
     *
     * @param \Toppy\Sendcloud\Model\Dimension|null $dimensions dimensions
     *
     * @return self
     */
    public function setDimensions($dimensions)
    {
        if (is_null($dimensions)) {
            throw new \InvalidArgumentException('non-nullable dimensions cannot be null');
        }
        $this->container['dimensions'] = $dimensions;

        return $this;
    }

    /**
     * Gets weight
     *
     * @return \Toppy\Sendcloud\Model\Weight
     */
    public function getWeight()
    {
        return $this->container['weight'];
    }

    /**
     * Sets weight
     *
     * @param \Toppy\Sendcloud\Model\Weight $weight weight
     *
     * @return self
     */
    public function setWeight($weight)
    {
        if (is_null($weight)) {
            throw new \InvalidArgumentException('non-nullable weight cannot be null');
        }
        $this->container['weight'] = $weight;

        return $this;
    }

    /**
     * Gets colloCount
     *
     * @return int|null
     */
    public function getColloCount()
    {
        return $this->container['colloCount'];
    }

    /**
     * Sets colloCount
     *
     * @param int|null $colloCount The number of collos this return consists of
     *
     * @return self
     */
    public function setColloCount($colloCount)
    {
        if (is_null($colloCount)) {
            throw new \InvalidArgumentException('non-nullable colloCount cannot be null');
        }

        if (($colloCount < 1)) {
            throw new \InvalidArgumentException('invalid value for $colloCount when calling ModelReturn., must be bigger than or equal to 1.');
        }

        $this->container['colloCount'] = $colloCount;

        return $this;
    }

    /**
     * Gets parcelItems
     *
     * @return \Toppy\Sendcloud\Model\ParcelItemReturnsDetails[]|null
     */
    public function getParcelItems()
    {
        return $this->container['parcelItems'];
    }

    /**
     * Sets parcelItems
     *
     * @param \Toppy\Sendcloud\Model\ParcelItemReturnsDetails[]|null $parcelItems List of items contained in this return. Required outside EU.
     *
     * @return self
     */
    public function setParcelItems($parcelItems)
    {
        if (is_null($parcelItems)) {
            throw new \InvalidArgumentException('non-nullable parcelItems cannot be null');
        }
        $this->container['parcelItems'] = $parcelItems;

        return $this;
    }

    /**
     * Gets sendTrackingEmails
     *
     * @return bool
     */
    public function getSendTrackingEmails()
    {
        return $this->container['sendTrackingEmails'];
    }

    /**
     * Sets sendTrackingEmails
     *
     * @param bool $sendTrackingEmails When true Sendcloud will send out the default track and trace emails
     *
     * @return self
     */
    public function setSendTrackingEmails($sendTrackingEmails)
    {
        if (is_null($sendTrackingEmails)) {
            throw new \InvalidArgumentException('non-nullable sendTrackingEmails cannot be null');
        }
        $this->container['sendTrackingEmails'] = $sendTrackingEmails;

        return $this;
    }

    /**
     * Gets brandId
     *
     * @return int|null
     */
    public function getBrandId()
    {
        return $this->container['brandId'];
    }

    /**
     * Sets brandId
     *
     * @param int|null $brandId The ID of the brand this Return belongs to.
     *
     * @return self
     */
    public function setBrandId($brandId)
    {
        if (is_null($brandId)) {
            throw new \InvalidArgumentException('non-nullable brandId cannot be null');
        }

        if (($brandId < 1)) {
            throw new \InvalidArgumentException('invalid value for $brandId when calling ModelReturn., must be bigger than or equal to 1.');
        }

        $this->container['brandId'] = $brandId;

        return $this;
    }

    /**
     * Gets labelUrl
     *
     * @return string|null
     * @deprecated
     */
    public function getLabelUrl()
    {
        return $this->container['labelUrl'];
    }

    /**
     * Sets labelUrl
     *
     * @param string|null $labelUrl URL to download the label. This can be `null` because it might not be announced yet. **Deprecated** in favour of the `label` field.
     *
     * @return self
     * @deprecated
     */
    public function setLabelUrl($labelUrl)
    {
        if (is_null($labelUrl)) {
            throw new \InvalidArgumentException('non-nullable labelUrl cannot be null');
        }
        $this->container['labelUrl'] = $labelUrl;

        return $this;
    }

    /**
     * Gets label
     *
     * @return \Toppy\Sendcloud\Model\ReturnLabel|null
     */
    public function getLabel()
    {
        return $this->container['label'];
    }

    /**
     * Sets label
     *
     * @param \Toppy\Sendcloud\Model\ReturnLabel|null $label label
     *
     * @return self
     */
    public function setLabel($label)
    {
        if (is_null($label)) {
            throw new \InvalidArgumentException('non-nullable label cannot be null');
        }
        $this->container['label'] = $label;

        return $this;
    }

    /**
     * Gets labelCost
     *
     * @return \Toppy\Sendcloud\Model\Price|null
     */
    public function getLabelCost()
    {
        return $this->container['labelCost'];
    }

    /**
     * Sets labelCost
     *
     * @param \Toppy\Sendcloud\Model\Price|null $labelCost labelCost
     *
     * @return self
     */
    public function setLabelCost($labelCost)
    {
        if (is_null($labelCost)) {
            throw new \InvalidArgumentException('non-nullable labelCost cannot be null');
        }
        $this->container['labelCost'] = $labelCost;

        return $this;
    }

    /**
     * Gets insurance
     *
     * @return bool|null
     */
    public function getInsurance()
    {
        return $this->container['insurance'];
    }

    /**
     * Sets insurance
     *
     * @param bool|null $insurance Whether the return parcel is insured
     *
     * @return self
     */
    public function setInsurance($insurance)
    {
        if (is_null($insurance)) {
            throw new \InvalidArgumentException('non-nullable insurance cannot be null');
        }
        $this->container['insurance'] = $insurance;

        return $this;
    }

    /**
     * Gets trackingNumber
     *
     * @return string|null
     */
    public function getTrackingNumber()
    {
        return $this->container['trackingNumber'];
    }

    /**
     * Sets trackingNumber
     *
     * @param string|null $trackingNumber This can be null because it might not be announced yet.
     *
     * @return self
     */
    public function setTrackingNumber($trackingNumber)
    {
        if (is_null($trackingNumber)) {
            throw new \InvalidArgumentException('non-nullable trackingNumber cannot be null');
        }
        $this->container['trackingNumber'] = $trackingNumber;

        return $this;
    }

    /**
     * Gets trackingUrl
     *
     * @return string|null
     */
    public function getTrackingUrl()
    {
        return $this->container['trackingUrl'];
    }

    /**
     * Sets trackingUrl
     *
     * @param string|null $trackingUrl URL to track your return. This can be null because it might not be announced yet.
     *
     * @return self
     */
    public function setTrackingUrl($trackingUrl)
    {
        if (is_null($trackingUrl)) {
            throw new \InvalidArgumentException('non-nullable trackingUrl cannot be null');
        }
        $this->container['trackingUrl'] = $trackingUrl;

        return $this;
    }

    /**
     * Gets isCancellable
     *
     * @return bool
     */
    public function getIsCancellable()
    {
        return $this->container['isCancellable'];
    }

    /**
     * Sets isCancellable
     *
     * @param bool $isCancellable the incoming parcel of this return can be cancelled
     *
     * @return self
     */
    public function setIsCancellable($isCancellable)
    {
        if (is_null($isCancellable)) {
            throw new \InvalidArgumentException('non-nullable isCancellable cannot be null');
        }
        $this->container['isCancellable'] = $isCancellable;

        return $this;
    }

    /**
     * Gets statusHistory
     *
     * @return \Toppy\Sendcloud\Model\DetailedTrackingBlobStatus[]
     */
    public function getStatusHistory()
    {
        return $this->container['statusHistory'];
    }

    /**
     * Sets statusHistory
     *
     * @param \Toppy\Sendcloud\Model\DetailedTrackingBlobStatus[] $statusHistory List with the timeline of your return status
     *
     * @return self
     */
    public function setStatusHistory($statusHistory)
    {
        if (is_null($statusHistory)) {
            throw new \InvalidArgumentException('non-nullable statusHistory cannot be null');
        }


        if ((count($statusHistory) < 1)) {
            throw new \InvalidArgumentException('invalid length for $statusHistory when calling ModelReturn., number of items must be greater than or equal to 1.');
        }
        $this->container['statusHistory'] = $statusHistory;

        return $this;
    }

    /**
     * Gets createdAt
     *
     * @return \DateTime
     */
    public function getCreatedAt()
    {
        return $this->container['createdAt'];
    }

    /**
     * Sets createdAt
     *
     * @param \DateTime $createdAt Date and time of creation of this return
     *
     * @return self
     */
    public function setCreatedAt($createdAt)
    {
        if (is_null($createdAt)) {
            throw new \InvalidArgumentException('non-nullable createdAt cannot be null');
        }
        $this->container['createdAt'] = $createdAt;

        return $this;
    }

    /**
     * Gets deliveredAt
     *
     * @return float|null
     * @deprecated
     */
    public function getDeliveredAt()
    {
        return $this->container['deliveredAt'];
    }

    /**
     * Sets deliveredAt
     *
     * @param float|null $deliveredAt A unix timestamp indicating the delivery time of this return. **Deprecated** in favour of the `delivered_at_iso` field.
     *
     * @return self
     * @deprecated
     */
    public function setDeliveredAt($deliveredAt)
    {
        if (is_null($deliveredAt)) {
            throw new \InvalidArgumentException('non-nullable deliveredAt cannot be null');
        }
        $this->container['deliveredAt'] = $deliveredAt;

        return $this;
    }

    /**
     * Gets deliveredAtIso
     *
     * @return \DateTime|null
     */
    public function getDeliveredAtIso()
    {
        return $this->container['deliveredAtIso'];
    }

    /**
     * Sets deliveredAtIso
     *
     * @param \DateTime|null $deliveredAtIso Date and time of delivery of this return
     *
     * @return self
     */
    public function setDeliveredAtIso($deliveredAtIso)
    {
        if (is_null($deliveredAtIso)) {
            throw new \InvalidArgumentException('non-nullable deliveredAtIso cannot be null');
        }
        $this->container['deliveredAtIso'] = $deliveredAtIso;

        return $this;
    }

    /**
     * Gets reason
     *
     * @return \Toppy\Sendcloud\Model\ReturnReason|null
     */
    public function getReason()
    {
        return $this->container['reason'];
    }

    /**
     * Sets reason
     *
     * @param \Toppy\Sendcloud\Model\ReturnReason|null $reason reason
     *
     * @return self
     */
    public function setReason($reason)
    {
        if (is_null($reason)) {
            throw new \InvalidArgumentException('non-nullable reason cannot be null');
        }
        $this->container['reason'] = $reason;

        return $this;
    }

    /**
     * Gets refund
     *
     * @return \Toppy\Sendcloud\Model\ReturnRefund|null
     */
    public function getRefund()
    {
        return $this->container['refund'];
    }

    /**
     * Sets refund
     *
     * @param \Toppy\Sendcloud\Model\ReturnRefund|null $refund refund
     *
     * @return self
     */
    public function setRefund($refund)
    {
        if (is_null($refund)) {
            throw new \InvalidArgumentException('non-nullable refund cannot be null');
        }
        $this->container['refund'] = $refund;

        return $this;
    }

    /**
     * Gets returnFee
     *
     * @return \Toppy\Sendcloud\Model\PriceWithAnyCurrency|null
     */
    public function getReturnFee()
    {
        return $this->container['returnFee'];
    }

    /**
     * Sets returnFee
     *
     * @param \Toppy\Sendcloud\Model\PriceWithAnyCurrency|null $returnFee returnFee
     *
     * @return self
     */
    public function setReturnFee($returnFee)
    {
        if (is_null($returnFee)) {
            throw new \InvalidArgumentException('non-nullable returnFee cannot be null');
        }
        $this->container['returnFee'] = $returnFee;

        return $this;
    }

    /**
     * Gets orderNumber
     *
     * @return string|null
     */
    public function getOrderNumber()
    {
        return $this->container['orderNumber'];
    }

    /**
     * Sets orderNumber
     *
     * @param string|null $orderNumber Order number filled by the user
     *
     * @return self
     */
    public function setOrderNumber($orderNumber)
    {
        if (is_null($orderNumber)) {
            throw new \InvalidArgumentException('non-nullable orderNumber cannot be null');
        }
        $this->container['orderNumber'] = $orderNumber;

        return $this;
    }

    /**
     * Gets contract
     *
     * @return int|null
     */
    public function getContract()
    {
        return $this->container['contract'];
    }

    /**
     * Sets contract
     *
     * @param int|null $contract ID of the contract used to ship this return
     *
     * @return self
     */
    public function setContract($contract)
    {
        if (is_null($contract)) {
            throw new \InvalidArgumentException('non-nullable contract cannot be null');
        }
        $this->container['contract'] = $contract;

        return $this;
    }

    /**
     * Gets customsInvoiceNr
     *
     * @return string|null
     */
    public function getCustomsInvoiceNr()
    {
        return $this->container['customsInvoiceNr'];
    }

    /**
     * Sets customsInvoiceNr
     *
     * @param string|null $customsInvoiceNr Customs invoice number
     *
     * @return self
     */
    public function setCustomsInvoiceNr($customsInvoiceNr)
    {
        if (is_null($customsInvoiceNr)) {
            throw new \InvalidArgumentException('non-nullable customsInvoiceNr cannot be null');
        }
        $this->container['customsInvoiceNr'] = $customsInvoiceNr;

        return $this;
    }

    /**
     * Gets customsShipmentType
     *
     * @return int|null
     */
    public function getCustomsShipmentType()
    {
        return $this->container['customsShipmentType'];
    }

    /**
     * Sets customsShipmentType
     *
     * @param int|null $customsShipmentType Customs shipment type   * `0` - Gift   * `1` - Documents   * `2` - Commercial Goods   * `3` - Commercial Sample   * `4` - Returned Goods
     *
     * @return self
     */
    public function setCustomsShipmentType($customsShipmentType)
    {
        if (is_null($customsShipmentType)) {
            throw new \InvalidArgumentException('non-nullable customsShipmentType cannot be null');
        }
        $allowedValues = $this->getCustomsShipmentTypeAllowableValues();
        if (!in_array($customsShipmentType, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'customsShipmentType', must be one of '%s'",
                    $customsShipmentType,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['customsShipmentType'] = $customsShipmentType;

        return $this;
    }

    /**
     * Gets deliveryOption
     *
     * @return \Toppy\Sendcloud\Model\DeliveryOption|null
     */
    public function getDeliveryOption()
    {
        return $this->container['deliveryOption'];
    }

    /**
     * Sets deliveryOption
     *
     * @param \Toppy\Sendcloud\Model\DeliveryOption|null $deliveryOption deliveryOption
     *
     * @return self
     */
    public function setDeliveryOption($deliveryOption)
    {
        if (is_null($deliveryOption)) {
            throw new \InvalidArgumentException('non-nullable deliveryOption cannot be null');
        }
        $this->container['deliveryOption'] = $deliveryOption;

        return $this;
    }

    /**
     * Gets images
     *
     * @return \Toppy\Sendcloud\Model\ReturnImagesInner[]|null
     */
    public function getImages()
    {
        return $this->container['images'];
    }

    /**
     * Sets images
     *
     * @param \Toppy\Sendcloud\Model\ReturnImagesInner[]|null $images Images uploaded when creating a return via the Return Portal
     *
     * @return self
     */
    public function setImages($images)
    {
        if (is_null($images)) {
            throw new \InvalidArgumentException('non-nullable images cannot be null');
        }

        if ((count($images) > 10)) {
            throw new \InvalidArgumentException('invalid value for $images when calling ModelReturn., number of items must be less than or equal to 10.');
        }
        $this->container['images'] = $images;

        return $this;
    }

    /**
     * Gets status
     *
     * @return string|null
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param string|null $status The current status of the return
     *
     * @return self
     */
    public function setStatus($status)
    {
        if (is_null($status)) {
            throw new \InvalidArgumentException('non-nullable status cannot be null');
        }
        $allowedValues = $this->getStatusAllowableValues();
        if (!in_array($status, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'status', must be one of '%s'",
                    $status,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets customsInformation
     *
     * @return \Toppy\Sendcloud\Model\ParcelCustomsInformation|null
     */
    public function getCustomsInformation()
    {
        return $this->container['customsInformation'];
    }

    /**
     * Sets customsInformation
     *
     * @param \Toppy\Sendcloud\Model\ParcelCustomsInformation|null $customsInformation customsInformation
     *
     * @return self
     */
    public function setCustomsInformation($customsInformation)
    {
        if (is_null($customsInformation)) {
            throw new \InvalidArgumentException('non-nullable customsInformation cannot be null');
        }
        $this->container['customsInformation'] = $customsInformation;

        return $this;
    }

    /**
     * Gets errors
     *
     * @return \Toppy\Sendcloud\Model\ErrorObject[]|null
     */
    public function getErrors()
    {
        return $this->container['errors'];
    }

    /**
     * Sets errors
     *
     * @param \Toppy\Sendcloud\Model\ErrorObject[]|null $errors This array will contain errors such as carrier announcement errors.
     *
     * @return self
     */
    public function setErrors($errors)
    {
        if (is_null($errors)) {
            throw new \InvalidArgumentException('non-nullable errors cannot be null');
        }
        $this->container['errors'] = $errors;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


