<?php

declare(strict_types=1);

/**
 * ShipmentRequestWithRules
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Toppy\Sendcloud
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
/**
 * Sendcloud Public REST API
 *
 * Complete Sendcloud API v3 specification - merged from official sendcloud.dev documentation
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: contact@sendcloud.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.18.0
 */
/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
namespace Toppy\Sendcloud\Model;

use \ArrayAccess;
use \Toppy\Sendcloud\ObjectSerializer;

/**
 * ShipmentRequestWithRules Class Doc Comment
 *
 * @category Class
 * @description Asynchronous Shipment with Rules request object model
 * @package  Toppy\Sendcloud
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ShipmentRequestWithRules implements ModelInterface, ArrayAccess, \JsonSerializable, \Stringable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'shipment-request-with-rules';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'brandId' => 'int',
        'shipWith' => \Toppy\Sendcloud\Model\ShipWith::class,
        'fromAddress' => \Toppy\Sendcloud\Model\AddressWithRequiredFields::class,
        'toAddress' => \Toppy\Sendcloud\Model\AddressWithRequiredFields::class,
        'toServicePoint' => \Toppy\Sendcloud\Model\ServicePoint::class,
        'orderNumber' => 'string',
        'totalOrderPrice' => \Toppy\Sendcloud\Model\OptionalPrice::class,
        'reference' => 'string',
        'externalReferenceId' => 'string',
        'customsInformation' => \Toppy\Sendcloud\Model\CustomsInformationWithOptionalFields::class,
        'labelDetails' => \Toppy\Sendcloud\Model\LabelDetails::class,
        'deliveryDates' => \Toppy\Sendcloud\Model\DeliveryDates::class,
        'parcels' => '\Toppy\Sendcloud\Model\MulticolloParcelsArrayRequestWithOptionalFieldsParcelsInner[]',
        'applyShippingDefaults' => 'bool',
        'applyShippingRules' => 'bool',
        'deliveryIndicator' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'brandId' => null,
        'shipWith' => null,
        'fromAddress' => null,
        'toAddress' => null,
        'toServicePoint' => null,
        'orderNumber' => null,
        'totalOrderPrice' => null,
        'reference' => null,
        'externalReferenceId' => null,
        'customsInformation' => null,
        'labelDetails' => null,
        'deliveryDates' => null,
        'parcels' => null,
        'applyShippingDefaults' => null,
        'applyShippingRules' => null,
        'deliveryIndicator' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'brandId' => false,
        'shipWith' => false,
        'fromAddress' => false,
        'toAddress' => false,
        'toServicePoint' => false,
        'orderNumber' => false,
        'totalOrderPrice' => true,
        'reference' => false,
        'externalReferenceId' => false,
        'customsInformation' => false,
        'labelDetails' => false,
        'deliveryDates' => true,
        'parcels' => false,
        'applyShippingDefaults' => false,
        'applyShippingRules' => false,
        'deliveryIndicator' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->openAPINullablesSetToNull, true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'brandId' => 'brand_id',
        'shipWith' => 'ship_with',
        'fromAddress' => 'from_address',
        'toAddress' => 'to_address',
        'toServicePoint' => 'to_service_point',
        'orderNumber' => 'order_number',
        'totalOrderPrice' => 'total_order_price',
        'reference' => 'reference',
        'externalReferenceId' => 'external_reference_id',
        'customsInformation' => 'customs_information',
        'labelDetails' => 'label_details',
        'deliveryDates' => 'delivery_dates',
        'parcels' => 'parcels',
        'applyShippingDefaults' => 'apply_shipping_defaults',
        'applyShippingRules' => 'apply_shipping_rules',
        'deliveryIndicator' => 'delivery_indicator'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'brandId' => 'setBrandId',
        'shipWith' => 'setShipWith',
        'fromAddress' => 'setFromAddress',
        'toAddress' => 'setToAddress',
        'toServicePoint' => 'setToServicePoint',
        'orderNumber' => 'setOrderNumber',
        'totalOrderPrice' => 'setTotalOrderPrice',
        'reference' => 'setReference',
        'externalReferenceId' => 'setExternalReferenceId',
        'customsInformation' => 'setCustomsInformation',
        'labelDetails' => 'setLabelDetails',
        'deliveryDates' => 'setDeliveryDates',
        'parcels' => 'setParcels',
        'applyShippingDefaults' => 'setApplyShippingDefaults',
        'applyShippingRules' => 'setApplyShippingRules',
        'deliveryIndicator' => 'setDeliveryIndicator'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'brandId' => 'getBrandId',
        'shipWith' => 'getShipWith',
        'fromAddress' => 'getFromAddress',
        'toAddress' => 'getToAddress',
        'toServicePoint' => 'getToServicePoint',
        'orderNumber' => 'getOrderNumber',
        'totalOrderPrice' => 'getTotalOrderPrice',
        'reference' => 'getReference',
        'externalReferenceId' => 'getExternalReferenceId',
        'customsInformation' => 'getCustomsInformation',
        'labelDetails' => 'getLabelDetails',
        'deliveryDates' => 'getDeliveryDates',
        'parcels' => 'getParcels',
        'applyShippingDefaults' => 'getApplyShippingDefaults',
        'applyShippingRules' => 'getApplyShippingRules',
        'deliveryIndicator' => 'getDeliveryIndicator'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('brandId', $data ?? [], null);
        $this->setIfExists('shipWith', $data ?? [], null);
        $this->setIfExists('fromAddress', $data ?? [], null);
        $this->setIfExists('toAddress', $data ?? [], null);
        $this->setIfExists('toServicePoint', $data ?? [], null);
        $this->setIfExists('orderNumber', $data ?? [], null);
        $this->setIfExists('totalOrderPrice', $data ?? [], null);
        $this->setIfExists('reference', $data ?? [], null);
        $this->setIfExists('externalReferenceId', $data ?? [], null);
        $this->setIfExists('customsInformation', $data ?? [], null);
        $this->setIfExists('labelDetails', $data ?? [], null);
        $this->setIfExists('deliveryDates', $data ?? [], null);
        $this->setIfExists('parcels', $data ?? [], null);
        $this->setIfExists('applyShippingDefaults', $data ?? [], true);
        $this->setIfExists('applyShippingRules', $data ?? [], true);
        $this->setIfExists('deliveryIndicator', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param mixed  $defaultValue
     * @param array<string, mixed> $fields
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['toAddress'] === null) {
            $invalidProperties[] = "'toAddress' can't be null";
        }

        if (!is_null($this->container['parcels']) && (count($this->container['parcels']) > 50)) {
            $invalidProperties[] = "invalid value for 'parcels', number of items must be less than or equal to 50.";
        }

        if (!is_null($this->container['parcels']) && (count($this->container['parcels']) < 1)) {
            $invalidProperties[] = "invalid value for 'parcels', number of items must be greater than or equal to 1.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets brandId
     *
     * @return int|null
     */
    public function getBrandId()
    {
        return $this->container['brandId'];
    }

    /**
     * Sets brandId
     *
     * @param int|null $brandId The `id` of the brand. Brands can be added through the [Sendcloud platform](https://app.sendcloud.com/v2/settings/brands/list) and be retrieved (alongside their `id`) from the [Retrieve a list of brands](/api/v2/brands/retrieve-a-list-of-brands) endpoint.
     *
     * @return self
     */
    public function setBrandId($brandId)
    {
        if (is_null($brandId)) {
            throw new \InvalidArgumentException('non-nullable brandId cannot be null');
        }

        $this->container['brandId'] = $brandId;

        return $this;
    }

    /**
     * Gets shipWith
     *
     * @return \Toppy\Sendcloud\Model\ShipWith|null
     */
    public function getShipWith()
    {
        return $this->container['shipWith'];
    }

    /**
     * Sets shipWith
     *
     * @param \Toppy\Sendcloud\Model\ShipWith|null $shipWith shipWith
     *
     * @return self
     */
    public function setShipWith($shipWith)
    {
        if (is_null($shipWith)) {
            throw new \InvalidArgumentException('non-nullable shipWith cannot be null');
        }

        $this->container['shipWith'] = $shipWith;

        return $this;
    }

    /**
     * Gets fromAddress
     *
     * @return \Toppy\Sendcloud\Model\AddressWithRequiredFields|null
     */
    public function getFromAddress()
    {
        return $this->container['fromAddress'];
    }

    /**
     * Sets fromAddress
     *
     * @param \Toppy\Sendcloud\Model\AddressWithRequiredFields|null $fromAddress fromAddress
     *
     * @return self
     */
    public function setFromAddress($fromAddress)
    {
        if (is_null($fromAddress)) {
            throw new \InvalidArgumentException('non-nullable fromAddress cannot be null');
        }

        $this->container['fromAddress'] = $fromAddress;

        return $this;
    }

    /**
     * Gets toAddress
     *
     * @return \Toppy\Sendcloud\Model\AddressWithRequiredFields
     */
    public function getToAddress()
    {
        return $this->container['toAddress'];
    }

    /**
     * Sets toAddress
     *
     * @param \Toppy\Sendcloud\Model\AddressWithRequiredFields $toAddress toAddress
     *
     * @return self
     */
    public function setToAddress($toAddress)
    {
        if (is_null($toAddress)) {
            throw new \InvalidArgumentException('non-nullable toAddress cannot be null');
        }

        $this->container['toAddress'] = $toAddress;

        return $this;
    }

    /**
     * Gets toServicePoint
     *
     * @return \Toppy\Sendcloud\Model\ServicePoint|null
     */
    public function getToServicePoint()
    {
        return $this->container['toServicePoint'];
    }

    /**
     * Sets toServicePoint
     *
     * @param \Toppy\Sendcloud\Model\ServicePoint|null $toServicePoint toServicePoint
     *
     * @return self
     */
    public function setToServicePoint($toServicePoint)
    {
        if (is_null($toServicePoint)) {
            throw new \InvalidArgumentException('non-nullable toServicePoint cannot be null');
        }

        $this->container['toServicePoint'] = $toServicePoint;

        return $this;
    }

    /**
     * Gets orderNumber
     *
     * @return string|null
     */
    public function getOrderNumber()
    {
        return $this->container['orderNumber'];
    }

    /**
     * Sets orderNumber
     *
     * @param string|null $orderNumber Order number generated manually or by shop system
     *
     * @return self
     */
    public function setOrderNumber($orderNumber)
    {
        if (is_null($orderNumber)) {
            throw new \InvalidArgumentException('non-nullable orderNumber cannot be null');
        }

        $this->container['orderNumber'] = $orderNumber;

        return $this;
    }

    /**
     * Gets totalOrderPrice
     *
     * @return \Toppy\Sendcloud\Model\OptionalPrice|null
     */
    public function getTotalOrderPrice()
    {
        return $this->container['totalOrderPrice'];
    }

    /**
     * Sets totalOrderPrice
     *
     * @param \Toppy\Sendcloud\Model\OptionalPrice|null $totalOrderPrice totalOrderPrice
     *
     * @return self
     */
    public function setTotalOrderPrice($totalOrderPrice)
    {
        if (is_null($totalOrderPrice)) {
            $this->openAPINullablesSetToNull[] = 'totalOrderPrice';
        } else {
            $nullablesSetToNull = $this->openAPINullablesSetToNull;
            $index = array_search('totalOrderPrice', $nullablesSetToNull, true);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        $this->container['totalOrderPrice'] = $totalOrderPrice;

        return $this;
    }

    /**
     * Gets reference
     *
     * @return string|null
     */
    public function getReference()
    {
        return $this->container['reference'];
    }

    /**
     * Sets reference
     *
     * @param string|null $reference A reference that will be stored on the Shipment and returned in your responses. This is not sent to the carrier.
     *
     * @return self
     */
    public function setReference($reference)
    {
        if (is_null($reference)) {
            throw new \InvalidArgumentException('non-nullable reference cannot be null');
        }

        $this->container['reference'] = $reference;

        return $this;
    }

    /**
     * Gets externalReferenceId
     *
     * @return string|null
     */
    public function getExternalReferenceId()
    {
        return $this->container['externalReferenceId'];
    }

    /**
     * Sets externalReferenceId
     *
     * @param string|null $externalReferenceId An optional reference can be provided by the API user; if included, it must be unique across shipments of the user. Using the same reference more than once will result in a 409 HTTP status code and the associated object being returned.
     *
     * @return self
     */
    public function setExternalReferenceId($externalReferenceId)
    {
        if (is_null($externalReferenceId)) {
            throw new \InvalidArgumentException('non-nullable externalReferenceId cannot be null');
        }

        $this->container['externalReferenceId'] = $externalReferenceId;

        return $this;
    }

    /**
     * Gets customsInformation
     *
     * @return \Toppy\Sendcloud\Model\CustomsInformationWithOptionalFields|null
     */
    public function getCustomsInformation()
    {
        return $this->container['customsInformation'];
    }

    /**
     * Sets customsInformation
     *
     * @param \Toppy\Sendcloud\Model\CustomsInformationWithOptionalFields|null $customsInformation customsInformation
     *
     * @return self
     */
    public function setCustomsInformation($customsInformation)
    {
        if (is_null($customsInformation)) {
            throw new \InvalidArgumentException('non-nullable customsInformation cannot be null');
        }

        $this->container['customsInformation'] = $customsInformation;

        return $this;
    }

    /**
     * Gets labelDetails
     *
     * @return \Toppy\Sendcloud\Model\LabelDetails|null
     */
    public function getLabelDetails()
    {
        return $this->container['labelDetails'];
    }

    /**
     * Sets labelDetails
     *
     * @param \Toppy\Sendcloud\Model\LabelDetails|null $labelDetails labelDetails
     *
     * @return self
     */
    public function setLabelDetails($labelDetails)
    {
        if (is_null($labelDetails)) {
            throw new \InvalidArgumentException('non-nullable labelDetails cannot be null');
        }

        $this->container['labelDetails'] = $labelDetails;

        return $this;
    }

    /**
     * Gets deliveryDates
     *
     * @return \Toppy\Sendcloud\Model\DeliveryDates|null
     */
    public function getDeliveryDates()
    {
        return $this->container['deliveryDates'];
    }

    /**
     * Sets deliveryDates
     *
     * @param \Toppy\Sendcloud\Model\DeliveryDates|null $deliveryDates deliveryDates
     *
     * @return self
     */
    public function setDeliveryDates($deliveryDates)
    {
        if (is_null($deliveryDates)) {
            $this->openAPINullablesSetToNull[] = 'deliveryDates';
        } else {
            $nullablesSetToNull = $this->openAPINullablesSetToNull;
            $index = array_search('deliveryDates', $nullablesSetToNull, true);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        $this->container['deliveryDates'] = $deliveryDates;

        return $this;
    }

    /**
     * Gets parcels
     *
     * @return \Toppy\Sendcloud\Model\MulticolloParcelsArrayRequestWithOptionalFieldsParcelsInner[]|null
     */
    public function getParcels()
    {
        return $this->container['parcels'];
    }

    /**
     * Sets parcels
     *
     * @param \Toppy\Sendcloud\Model\MulticolloParcelsArrayRequestWithOptionalFieldsParcelsInner[]|null $parcels Represents each package of the shipment. Each carrier can have its own number of parcels limit per shipment, otherwise there is a restriction to a maximum of 50 parcels (default).
     *
     * @return self
     */
    public function setParcels($parcels)
    {
        if (is_null($parcels)) {
            throw new \InvalidArgumentException('non-nullable parcels cannot be null');
        }

        if ((count($parcels) > 50)) {
            throw new \InvalidArgumentException('invalid value for $parcels when calling ShipmentRequestWithRules., number of items must be less than or equal to 50.');
        }

        if ((count($parcels) < 1)) {
            throw new \InvalidArgumentException('invalid length for $parcels when calling ShipmentRequestWithRules., number of items must be greater than or equal to 1.');
        }

        $this->container['parcels'] = $parcels;

        return $this;
    }

    /**
     * Gets applyShippingDefaults
     *
     * @return bool|null
     */
    public function getApplyShippingDefaults()
    {
        return $this->container['applyShippingDefaults'];
    }

    /**
     * Sets applyShippingDefaults
     *
     * @param bool|null $applyShippingDefaults When set to `true`, the \"Default weight\", \"Preferred shipping method\" and \"Default export reason\" [shipping defaults](https://app.sendcloud.com/v2/shipping/shipping-defaults) will be applied, if they were not provided by the request payload.  **Note that the request payload values and shipping rules take precedence over these defaults.**
     *
     * @return self
     */
    public function setApplyShippingDefaults($applyShippingDefaults)
    {
        if (is_null($applyShippingDefaults)) {
            throw new \InvalidArgumentException('non-nullable applyShippingDefaults cannot be null');
        }

        $this->container['applyShippingDefaults'] = $applyShippingDefaults;

        return $this;
    }

    /**
     * Gets applyShippingRules
     *
     * @return bool|null
     */
    public function getApplyShippingRules()
    {
        return $this->container['applyShippingRules'];
    }

    /**
     * Sets applyShippingRules
     *
     * @param bool|null $applyShippingRules When set to `true`, [shipping rules](https://app.sendcloud.com/v2/shipping/rules) will be applied.  <Info>   **Note that rules take precedence over the values provided in the request payload and over the [shipping defaults](https://app.sendcloud.com/v2/shipping/shipping-defaults).**      For instance, if a contract is specified in one of the applicable rules for the shipment that is being requested, the contract value provided in the request payload will be ignored.      Also keep in mind that since orders created by the API do not appear in the Sendcloud platform's Incoming Orders overview, not all shipping rules can be applied. </Info>
     *
     * @return self
     */
    public function setApplyShippingRules($applyShippingRules)
    {
        if (is_null($applyShippingRules)) {
            throw new \InvalidArgumentException('non-nullable applyShippingRules cannot be null');
        }

        $this->container['applyShippingRules'] = $applyShippingRules;

        return $this;
    }

    /**
     * Gets deliveryIndicator
     *
     * @return string|null
     */
    public function getDeliveryIndicator()
    {
        return $this->container['deliveryIndicator'];
    }

    /**
     * Sets deliveryIndicator
     *
     * @param string|null $deliveryIndicator Free text that is intended for applying the **Checkout Delivery Method** condition in shipping rules.  Learn more about [Shipping rules](/docs/shipping/shipping-rules/).
     *
     * @return self
     */
    public function setDeliveryIndicator($deliveryIndicator)
    {
        if (is_null($deliveryIndicator)) {
            throw new \InvalidArgumentException('non-nullable deliveryIndicator cannot be null');
        }

        $this->container['deliveryIndicator'] = $deliveryIndicator;

        return $this;
    }

    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     */
    public function __toString(): string
    {
        return (string) json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
