<?php
/**
 * ShippingOption
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Toppy\Sendcloud\V3
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Sendcloud Public REST API
 *
 * Complete Sendcloud API v3 specification - merged from official sendcloud.dev documentation
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: contact@sendcloud.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.18.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Toppy\Sendcloud\V3\Model;

use \ArrayAccess;
use \Toppy\Sendcloud\V3\ObjectSerializer;

/**
 * ShippingOption Class Doc Comment
 *
 * @category Class
 * @description A shipping option is a shipping product that the carrier offers in combination with a unique set of shipping functionalities.
 * @package  Toppy\Sendcloud\V3
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ShippingOption implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'shipping-option';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'code' => 'string',
        'name' => 'string',
        'carrier' => '\Toppy\Sendcloud\V3\Model\Carrier',
        'product' => '\Toppy\Sendcloud\V3\Model\ShippingProduct',
        'functionalities' => '\Toppy\Sendcloud\V3\Model\CarrierShippingFunctionalities',
        'maxDimensions' => '\Toppy\Sendcloud\V3\Model\ShippingOptionsDimension',
        'weight' => '\Toppy\Sendcloud\V3\Model\ShippingQuoteWeight',
        'parcelBilledWeights' => '\Toppy\Sendcloud\V3\Model\ParcelBilledWeights[]',
        'contract' => '\Toppy\Sendcloud\V3\Model\Contract',
        'requirements' => '\Toppy\Sendcloud\V3\Model\Requirements',
        'chargingType' => 'string',
        'quotes' => '\Toppy\Sendcloud\V3\Model\ShippingQuote[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'code' => null,
        'name' => null,
        'carrier' => null,
        'product' => null,
        'functionalities' => null,
        'maxDimensions' => null,
        'weight' => null,
        'parcelBilledWeights' => null,
        'contract' => null,
        'requirements' => null,
        'chargingType' => null,
        'quotes' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'code' => false,
        'name' => false,
        'carrier' => false,
        'product' => false,
        'functionalities' => false,
        'maxDimensions' => false,
        'weight' => false,
        'parcelBilledWeights' => false,
        'contract' => false,
        'requirements' => false,
        'chargingType' => false,
        'quotes' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'code' => 'code',
        'name' => 'name',
        'carrier' => 'carrier',
        'product' => 'product',
        'functionalities' => 'functionalities',
        'maxDimensions' => 'max_dimensions',
        'weight' => 'weight',
        'parcelBilledWeights' => 'parcel_billed_weights',
        'contract' => 'contract',
        'requirements' => 'requirements',
        'chargingType' => 'charging_type',
        'quotes' => 'quotes'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'code' => 'setCode',
        'name' => 'setName',
        'carrier' => 'setCarrier',
        'product' => 'setProduct',
        'functionalities' => 'setFunctionalities',
        'maxDimensions' => 'setMaxDimensions',
        'weight' => 'setWeight',
        'parcelBilledWeights' => 'setParcelBilledWeights',
        'contract' => 'setContract',
        'requirements' => 'setRequirements',
        'chargingType' => 'setChargingType',
        'quotes' => 'setQuotes'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'code' => 'getCode',
        'name' => 'getName',
        'carrier' => 'getCarrier',
        'product' => 'getProduct',
        'functionalities' => 'getFunctionalities',
        'maxDimensions' => 'getMaxDimensions',
        'weight' => 'getWeight',
        'parcelBilledWeights' => 'getParcelBilledWeights',
        'contract' => 'getContract',
        'requirements' => 'getRequirements',
        'chargingType' => 'getChargingType',
        'quotes' => 'getQuotes'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const CHARGING_TYPE_FIRST_SCAN = 'first_scan';
    public const CHARGING_TYPE_LABEL_CREATION = 'label_creation';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getChargingTypeAllowableValues()
    {
        return [
            self::CHARGING_TYPE_FIRST_SCAN,
            self::CHARGING_TYPE_LABEL_CREATION,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('code', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('carrier', $data ?? [], null);
        $this->setIfExists('product', $data ?? [], null);
        $this->setIfExists('functionalities', $data ?? [], null);
        $this->setIfExists('maxDimensions', $data ?? [], null);
        $this->setIfExists('weight', $data ?? [], null);
        $this->setIfExists('parcelBilledWeights', $data ?? [], null);
        $this->setIfExists('contract', $data ?? [], null);
        $this->setIfExists('requirements', $data ?? [], null);
        $this->setIfExists('chargingType', $data ?? [], null);
        $this->setIfExists('quotes', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getChargingTypeAllowableValues();
        if (!is_null($this->container['chargingType']) && !in_array($this->container['chargingType'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'chargingType', must be one of '%s'",
                $this->container['chargingType'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets code
     *
     * @return string|null
     */
    public function getCode()
    {
        return $this->container['code'];
    }

    /**
     * Sets code
     *
     * @param string|null $code Unique identifier for this Shipping option. You can use this code to announce a parcel in the Parcel API.
     *
     * @return self
     */
    public function setCode($code)
    {
        if (is_null($code)) {
            throw new \InvalidArgumentException('non-nullable code cannot be null');
        }
        $this->container['code'] = $code;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string|null
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string|null $name Shipping option friendly name
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets carrier
     *
     * @return \Toppy\Sendcloud\V3\Model\Carrier|null
     */
    public function getCarrier()
    {
        return $this->container['carrier'];
    }

    /**
     * Sets carrier
     *
     * @param \Toppy\Sendcloud\V3\Model\Carrier|null $carrier carrier
     *
     * @return self
     */
    public function setCarrier($carrier)
    {
        if (is_null($carrier)) {
            throw new \InvalidArgumentException('non-nullable carrier cannot be null');
        }
        $this->container['carrier'] = $carrier;

        return $this;
    }

    /**
     * Gets product
     *
     * @return \Toppy\Sendcloud\V3\Model\ShippingProduct|null
     */
    public function getProduct()
    {
        return $this->container['product'];
    }

    /**
     * Sets product
     *
     * @param \Toppy\Sendcloud\V3\Model\ShippingProduct|null $product product
     *
     * @return self
     */
    public function setProduct($product)
    {
        if (is_null($product)) {
            throw new \InvalidArgumentException('non-nullable product cannot be null');
        }
        $this->container['product'] = $product;

        return $this;
    }

    /**
     * Gets functionalities
     *
     * @return \Toppy\Sendcloud\V3\Model\CarrierShippingFunctionalities|null
     */
    public function getFunctionalities()
    {
        return $this->container['functionalities'];
    }

    /**
     * Sets functionalities
     *
     * @param \Toppy\Sendcloud\V3\Model\CarrierShippingFunctionalities|null $functionalities functionalities
     *
     * @return self
     */
    public function setFunctionalities($functionalities)
    {
        if (is_null($functionalities)) {
            throw new \InvalidArgumentException('non-nullable functionalities cannot be null');
        }
        $this->container['functionalities'] = $functionalities;

        return $this;
    }

    /**
     * Gets maxDimensions
     *
     * @return \Toppy\Sendcloud\V3\Model\ShippingOptionsDimension|null
     */
    public function getMaxDimensions()
    {
        return $this->container['maxDimensions'];
    }

    /**
     * Sets maxDimensions
     *
     * @param \Toppy\Sendcloud\V3\Model\ShippingOptionsDimension|null $maxDimensions maxDimensions
     *
     * @return self
     */
    public function setMaxDimensions($maxDimensions)
    {
        if (is_null($maxDimensions)) {
            throw new \InvalidArgumentException('non-nullable maxDimensions cannot be null');
        }
        $this->container['maxDimensions'] = $maxDimensions;

        return $this;
    }

    /**
     * Gets weight
     *
     * @return \Toppy\Sendcloud\V3\Model\ShippingQuoteWeight|null
     */
    public function getWeight()
    {
        return $this->container['weight'];
    }

    /**
     * Sets weight
     *
     * @param \Toppy\Sendcloud\V3\Model\ShippingQuoteWeight|null $weight weight
     *
     * @return self
     */
    public function setWeight($weight)
    {
        if (is_null($weight)) {
            throw new \InvalidArgumentException('non-nullable weight cannot be null');
        }
        $this->container['weight'] = $weight;

        return $this;
    }

    /**
     * Gets parcelBilledWeights
     *
     * @return \Toppy\Sendcloud\V3\Model\ParcelBilledWeights[]|null
     */
    public function getParcelBilledWeights()
    {
        return $this->container['parcelBilledWeights'];
    }

    /**
     * Sets parcelBilledWeights
     *
     * @param \Toppy\Sendcloud\V3\Model\ParcelBilledWeights[]|null $parcelBilledWeights If `dimensions` are provided, the volumetric weight will be calculated. The billed weight will indicate which is the highest of the regular weight and the volumetric weight.
     *
     * @return self
     */
    public function setParcelBilledWeights($parcelBilledWeights)
    {
        if (is_null($parcelBilledWeights)) {
            throw new \InvalidArgumentException('non-nullable parcelBilledWeights cannot be null');
        }
        $this->container['parcelBilledWeights'] = $parcelBilledWeights;

        return $this;
    }

    /**
     * Gets contract
     *
     * @return \Toppy\Sendcloud\V3\Model\Contract|null
     */
    public function getContract()
    {
        return $this->container['contract'];
    }

    /**
     * Sets contract
     *
     * @param \Toppy\Sendcloud\V3\Model\Contract|null $contract contract
     *
     * @return self
     */
    public function setContract($contract)
    {
        if (is_null($contract)) {
            throw new \InvalidArgumentException('non-nullable contract cannot be null');
        }
        $this->container['contract'] = $contract;

        return $this;
    }

    /**
     * Gets requirements
     *
     * @return \Toppy\Sendcloud\V3\Model\Requirements|null
     */
    public function getRequirements()
    {
        return $this->container['requirements'];
    }

    /**
     * Sets requirements
     *
     * @param \Toppy\Sendcloud\V3\Model\Requirements|null $requirements requirements
     *
     * @return self
     */
    public function setRequirements($requirements)
    {
        if (is_null($requirements)) {
            throw new \InvalidArgumentException('non-nullable requirements cannot be null');
        }
        $this->container['requirements'] = $requirements;

        return $this;
    }

    /**
     * Gets chargingType
     *
     * @return string|null
     */
    public function getChargingType()
    {
        return $this->container['chargingType'];
    }

    /**
     * Sets chargingType
     *
     * @param string|null $chargingType Specifies the timing of Sendcloud's invoicing for the shipping label.  If set to `label_creation`, the label is invoiced at the moment it is created.  If set to `first_scan`, the label is only invoiced when the carrier first scans the parcel.  The `first_scan` value is only supported for return shipping options.
     *
     * @return self
     */
    public function setChargingType($chargingType)
    {
        if (is_null($chargingType)) {
            throw new \InvalidArgumentException('non-nullable chargingType cannot be null');
        }
        $allowedValues = $this->getChargingTypeAllowableValues();
        if (!in_array($chargingType, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'chargingType', must be one of '%s'",
                    $chargingType,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['chargingType'] = $chargingType;

        return $this;
    }

    /**
     * Gets quotes
     *
     * @return \Toppy\Sendcloud\V3\Model\ShippingQuote[]|null
     */
    public function getQuotes()
    {
        return $this->container['quotes'];
    }

    /**
     * Sets quotes
     *
     * @param \Toppy\Sendcloud\V3\Model\ShippingQuote[]|null $quotes List of available quotes.  Quotes will only be calculated if:    - `from_country_code` and `to_country_code` are to provided. - Direct contract prices are provided for the returned shipping options.
     *
     * @return self
     */
    public function setQuotes($quotes)
    {
        if (is_null($quotes)) {
            throw new \InvalidArgumentException('non-nullable quotes cannot be null');
        }
        $this->container['quotes'] = $quotes;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


