<?php
/**
 * DeliveryOptionsApi
 * PHP version 7.2
 *
 * @category Class
 * @package  Toppy\Sendcloud
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Sendcloud Public REST API
 *
 * Complete Sendcloud API v3 specification - merged from official Stoplight documentation bundles
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: contact@sendcloud.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.18.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Toppy\Sendcloud\Api;

use GuzzleHttp\Psr7\MultipartStream;
use Http\Client\Common\Plugin\ErrorPlugin;
use Http\Client\Common\Plugin\RedirectPlugin;
use Http\Client\Common\PluginClient;
use Http\Client\Common\PluginClientFactory;
use Http\Client\Exception\HttpException;
use Http\Client\HttpAsyncClient;
use Http\Discovery\HttpAsyncClientDiscovery;
use Http\Discovery\Psr17FactoryDiscovery;
use Http\Discovery\Psr18ClientDiscovery;
use Http\Message\RequestFactory;
use Http\Promise\Promise;
use Toppy\Sendcloud\ApiException;
use Toppy\Sendcloud\Configuration;
use Toppy\Sendcloud\DebugPlugin;
use Toppy\Sendcloud\HeaderSelector;
use Toppy\Sendcloud\FormDataProcessor;
use Toppy\Sendcloud\ObjectSerializer;
use Psr\Http\Client\ClientExceptionInterface;
use Psr\Http\Client\ClientInterface;
use Psr\Http\Message\RequestFactoryInterface;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use Psr\Http\Message\StreamFactoryInterface;
use Psr\Http\Message\UriFactoryInterface;
use Psr\Http\Message\UriInterface;
use function sprintf;

/**
 * DeliveryOptionsApi Class Doc Comment
 *
 * @category Class
 * @package  Toppy\Sendcloud
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DeliveryOptionsApi
{
    /**
     * @var PluginClient
     */
    protected $httpClient;

    /**
     * @var PluginClient
     */
    protected $httpAsyncClient;

    /**
     * @var UriFactoryInterface
     */
    protected $uriFactory;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /**
     * @var RequestFactoryInterface
     */
    protected $requestFactory;

    /**
     * @var StreamFactoryInterface
     */
    protected $streamFactory;

    public function __construct(
        ?ClientInterface $httpClient = null,
        ?Configuration $config = null,
        ?HttpAsyncClient $httpAsyncClient = null,
        ?UriFactoryInterface $uriFactory = null,
        ?RequestFactoryInterface $requestFactory = null,
        ?StreamFactoryInterface $streamFactory = null,
        ?HeaderSelector $selector = null,
        ?array $plugins = null,
        $hostIndex = 0
    ) {
        $this->config = $config ?? (new Configuration())->setHost('https://account.sendcloud.com');
        $this->requestFactory = $requestFactory ?? Psr17FactoryDiscovery::findRequestFactory();
        $this->streamFactory = $streamFactory ?? Psr17FactoryDiscovery::findStreamFactory();

        $plugins = $plugins ?? [
            new RedirectPlugin(['strict' => true]),
            new ErrorPlugin(),
        ];

        if ($this->config->getDebug()) {
            $plugins[] = new DebugPlugin(fopen($this->config->getDebugFile(), 'ab'));
        }

        $this->httpClient = (new PluginClientFactory())->createClient(
            $httpClient ?? Psr18ClientDiscovery::find(),
            $plugins
        );

        $this->httpAsyncClient = (new PluginClientFactory())->createClient(
            $httpAsyncClient ?? HttpAsyncClientDiscovery::find(),
            $plugins
        );

        $this->uriFactory = $uriFactory ?? Psr17FactoryDiscovery::findUriFactory();

        $this->headerSelector = $selector ?? new HeaderSelector();

        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation scPublicV3CheckoutApiGetDeliveryOptions
     *
     * Retrieve a list of delivery options
     *
     * @param  string $configurationId The unique ID of the checkout configuration used to retrieve delivery options (required)
     * @param  int $weightValue The total weight of the cart or order, specified in grams by default. This parameter is used to select the most suitable shipping option. (required)
     * @param  string $totalOrderValue The total price of the cart or order, specified in the currency of the checkout configuration. This parameter is used to calculate the shipping rate if rates are configured for the delivery method. It can also be used to determine if free shipping is applicable based on the configured pricing rules. (required)
     * @param  mixed $fromCountryCode The sender&#39;s country code for the shipment, formatted as an [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) code (required)
     * @param  mixed $toCountryCode The recipient&#39;s country code for the shipment, formatted as an [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) code (required)
     * @param  string $checkoutIdentifierType Specifies how to retrieve the shipping label. Currently, only the &#x60;shipping_option_code&#x60; type is supported.  When this type is used, the &#x60;checkout_identifier&#x60; field in each delivery option contains the shipping option code, which is required to &lt;a href&#x3D;\&quot;https://api.sendcloud.dev/docs/sendcloud-public-api/shipments/operations/create-a-shipment\&quot;&gt;create a shipment&lt;/a&gt; (optional, default to 'shipping_option_code')
     * @param  string $toPostalCode The recipient&#39;s postal code. Use this in combination with &lt;a href&#x3D;\&quot;https://support.sendcloud.com/hc/en-us/articles/18580048370705-Checkout-rules\&quot;&gt;Checkout Rules&lt;/a&gt; to show or hide delivery options for specific locations. (optional)
     * @param  float $parcelLength The parcel&#39;s length in centimeters (e.g., \&quot;48\&quot; or \&quot;52.3\&quot;) (optional)
     * @param  float $parcelWidth The parcel&#39;s width in centimeters (e.g., \&quot;48\&quot; or \&quot;52.3\&quot;) (optional)
     * @param  float $parcelHeight The parcel&#39;s height in centimeters (e.g., \&quot;48\&quot; or \&quot;52.3\&quot;) (optional)
     * @param  string $checkoutMetadata An arbitrary text field that can be used with &lt;a href&#x3D;\&quot;https://support.sendcloud.com/hc/en-us/articles/18580048370705-Checkout-rules\&quot;&gt;Checkout Rules&lt;/a&gt; to control which delivery options are displayed during checkout. For example, you might use it to pass a product SKU, goods category, or any other custom property to show or hide specific delivery options during checkout (optional)
     *
     * @throws \Toppy\Sendcloud\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Toppy\Sendcloud\Model\DeliveryOptionsResponse|\Toppy\Sendcloud\Model\Errors|\Toppy\Sendcloud\Model\Errors
     */
    public function scPublicV3CheckoutApiGetDeliveryOptions($configurationId, $weightValue, $totalOrderValue, $fromCountryCode, $toCountryCode, $checkoutIdentifierType = 'shipping_option_code', $toPostalCode = null, $parcelLength = null, $parcelWidth = null, $parcelHeight = null, $checkoutMetadata = null)
    {
        list($response) = $this->scPublicV3CheckoutApiGetDeliveryOptionsWithHttpInfo($configurationId, $weightValue, $totalOrderValue, $fromCountryCode, $toCountryCode, $checkoutIdentifierType, $toPostalCode, $parcelLength, $parcelWidth, $parcelHeight, $checkoutMetadata);
        return $response;
    }

    /**
     * Operation scPublicV3CheckoutApiGetDeliveryOptionsWithHttpInfo
     *
     * Retrieve a list of delivery options
     *
     * @param  string $configurationId The unique ID of the checkout configuration used to retrieve delivery options (required)
     * @param  int $weightValue The total weight of the cart or order, specified in grams by default. This parameter is used to select the most suitable shipping option. (required)
     * @param  string $totalOrderValue The total price of the cart or order, specified in the currency of the checkout configuration. This parameter is used to calculate the shipping rate if rates are configured for the delivery method. It can also be used to determine if free shipping is applicable based on the configured pricing rules. (required)
     * @param  mixed $fromCountryCode The sender&#39;s country code for the shipment, formatted as an [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) code (required)
     * @param  mixed $toCountryCode The recipient&#39;s country code for the shipment, formatted as an [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) code (required)
     * @param  string $checkoutIdentifierType Specifies how to retrieve the shipping label. Currently, only the &#x60;shipping_option_code&#x60; type is supported.  When this type is used, the &#x60;checkout_identifier&#x60; field in each delivery option contains the shipping option code, which is required to &lt;a href&#x3D;\&quot;https://api.sendcloud.dev/docs/sendcloud-public-api/shipments/operations/create-a-shipment\&quot;&gt;create a shipment&lt;/a&gt; (optional, default to 'shipping_option_code')
     * @param  string $toPostalCode The recipient&#39;s postal code. Use this in combination with &lt;a href&#x3D;\&quot;https://support.sendcloud.com/hc/en-us/articles/18580048370705-Checkout-rules\&quot;&gt;Checkout Rules&lt;/a&gt; to show or hide delivery options for specific locations. (optional)
     * @param  float $parcelLength The parcel&#39;s length in centimeters (e.g., \&quot;48\&quot; or \&quot;52.3\&quot;) (optional)
     * @param  float $parcelWidth The parcel&#39;s width in centimeters (e.g., \&quot;48\&quot; or \&quot;52.3\&quot;) (optional)
     * @param  float $parcelHeight The parcel&#39;s height in centimeters (e.g., \&quot;48\&quot; or \&quot;52.3\&quot;) (optional)
     * @param  string $checkoutMetadata An arbitrary text field that can be used with &lt;a href&#x3D;\&quot;https://support.sendcloud.com/hc/en-us/articles/18580048370705-Checkout-rules\&quot;&gt;Checkout Rules&lt;/a&gt; to control which delivery options are displayed during checkout. For example, you might use it to pass a product SKU, goods category, or any other custom property to show or hide specific delivery options during checkout (optional)
     *
     * @throws \Toppy\Sendcloud\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Toppy\Sendcloud\Model\DeliveryOptionsResponse|\Toppy\Sendcloud\Model\Errors|\Toppy\Sendcloud\Model\Errors, HTTP status code, HTTP response headers (array of strings)
     */
    public function scPublicV3CheckoutApiGetDeliveryOptionsWithHttpInfo($configurationId, $weightValue, $totalOrderValue, $fromCountryCode, $toCountryCode, $checkoutIdentifierType = 'shipping_option_code', $toPostalCode = null, $parcelLength = null, $parcelWidth = null, $parcelHeight = null, $checkoutMetadata = null)
    {
        $request = $this->scPublicV3CheckoutApiGetDeliveryOptionsRequest($configurationId, $weightValue, $totalOrderValue, $fromCountryCode, $toCountryCode, $checkoutIdentifierType, $toPostalCode, $parcelLength, $parcelWidth, $parcelHeight, $checkoutMetadata);

        try {
            try {
                $response = $this->httpClient->sendRequest($request);
            } catch (HttpException $e) {
                $response = $e->getResponse();
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $response->getStatusCode(),
                        (string) $request->getUri()
                    ),
                    $request,
                    $response,
                    $e
                );
            } catch (ClientExceptionInterface $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $request,
                    null,
                    $e
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\Toppy\Sendcloud\Model\DeliveryOptionsResponse',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\Toppy\Sendcloud\Model\Errors',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\Toppy\Sendcloud\Model\Errors',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $request,
                    $response
                );
            }

            return $this->handleResponseWithDataType(
                '\Toppy\Sendcloud\Model\DeliveryOptionsResponse',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Toppy\Sendcloud\Model\DeliveryOptionsResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Toppy\Sendcloud\Model\Errors',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Toppy\Sendcloud\Model\Errors',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation scPublicV3CheckoutApiGetDeliveryOptionsAsync
     *
     * Retrieve a list of delivery options
     *
     * @param  string $configurationId The unique ID of the checkout configuration used to retrieve delivery options (required)
     * @param  int $weightValue The total weight of the cart or order, specified in grams by default. This parameter is used to select the most suitable shipping option. (required)
     * @param  string $totalOrderValue The total price of the cart or order, specified in the currency of the checkout configuration. This parameter is used to calculate the shipping rate if rates are configured for the delivery method. It can also be used to determine if free shipping is applicable based on the configured pricing rules. (required)
     * @param  mixed $fromCountryCode The sender&#39;s country code for the shipment, formatted as an [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) code (required)
     * @param  mixed $toCountryCode The recipient&#39;s country code for the shipment, formatted as an [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) code (required)
     * @param  string $checkoutIdentifierType Specifies how to retrieve the shipping label. Currently, only the &#x60;shipping_option_code&#x60; type is supported.  When this type is used, the &#x60;checkout_identifier&#x60; field in each delivery option contains the shipping option code, which is required to &lt;a href&#x3D;\&quot;https://api.sendcloud.dev/docs/sendcloud-public-api/shipments/operations/create-a-shipment\&quot;&gt;create a shipment&lt;/a&gt; (optional, default to 'shipping_option_code')
     * @param  string $toPostalCode The recipient&#39;s postal code. Use this in combination with &lt;a href&#x3D;\&quot;https://support.sendcloud.com/hc/en-us/articles/18580048370705-Checkout-rules\&quot;&gt;Checkout Rules&lt;/a&gt; to show or hide delivery options for specific locations. (optional)
     * @param  float $parcelLength The parcel&#39;s length in centimeters (e.g., \&quot;48\&quot; or \&quot;52.3\&quot;) (optional)
     * @param  float $parcelWidth The parcel&#39;s width in centimeters (e.g., \&quot;48\&quot; or \&quot;52.3\&quot;) (optional)
     * @param  float $parcelHeight The parcel&#39;s height in centimeters (e.g., \&quot;48\&quot; or \&quot;52.3\&quot;) (optional)
     * @param  string $checkoutMetadata An arbitrary text field that can be used with &lt;a href&#x3D;\&quot;https://support.sendcloud.com/hc/en-us/articles/18580048370705-Checkout-rules\&quot;&gt;Checkout Rules&lt;/a&gt; to control which delivery options are displayed during checkout. For example, you might use it to pass a product SKU, goods category, or any other custom property to show or hide specific delivery options during checkout (optional)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function scPublicV3CheckoutApiGetDeliveryOptionsAsync($configurationId, $weightValue, $totalOrderValue, $fromCountryCode, $toCountryCode, $checkoutIdentifierType = 'shipping_option_code', $toPostalCode = null, $parcelLength = null, $parcelWidth = null, $parcelHeight = null, $checkoutMetadata = null)
    {
        return $this->scPublicV3CheckoutApiGetDeliveryOptionsAsyncWithHttpInfo($configurationId, $weightValue, $totalOrderValue, $fromCountryCode, $toCountryCode, $checkoutIdentifierType, $toPostalCode, $parcelLength, $parcelWidth, $parcelHeight, $checkoutMetadata)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation scPublicV3CheckoutApiGetDeliveryOptionsAsyncWithHttpInfo
     *
     * Retrieve a list of delivery options
     *
     * @param  string $configurationId The unique ID of the checkout configuration used to retrieve delivery options (required)
     * @param  int $weightValue The total weight of the cart or order, specified in grams by default. This parameter is used to select the most suitable shipping option. (required)
     * @param  string $totalOrderValue The total price of the cart or order, specified in the currency of the checkout configuration. This parameter is used to calculate the shipping rate if rates are configured for the delivery method. It can also be used to determine if free shipping is applicable based on the configured pricing rules. (required)
     * @param  mixed $fromCountryCode The sender&#39;s country code for the shipment, formatted as an [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) code (required)
     * @param  mixed $toCountryCode The recipient&#39;s country code for the shipment, formatted as an [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) code (required)
     * @param  string $checkoutIdentifierType Specifies how to retrieve the shipping label. Currently, only the &#x60;shipping_option_code&#x60; type is supported.  When this type is used, the &#x60;checkout_identifier&#x60; field in each delivery option contains the shipping option code, which is required to &lt;a href&#x3D;\&quot;https://api.sendcloud.dev/docs/sendcloud-public-api/shipments/operations/create-a-shipment\&quot;&gt;create a shipment&lt;/a&gt; (optional, default to 'shipping_option_code')
     * @param  string $toPostalCode The recipient&#39;s postal code. Use this in combination with &lt;a href&#x3D;\&quot;https://support.sendcloud.com/hc/en-us/articles/18580048370705-Checkout-rules\&quot;&gt;Checkout Rules&lt;/a&gt; to show or hide delivery options for specific locations. (optional)
     * @param  float $parcelLength The parcel&#39;s length in centimeters (e.g., \&quot;48\&quot; or \&quot;52.3\&quot;) (optional)
     * @param  float $parcelWidth The parcel&#39;s width in centimeters (e.g., \&quot;48\&quot; or \&quot;52.3\&quot;) (optional)
     * @param  float $parcelHeight The parcel&#39;s height in centimeters (e.g., \&quot;48\&quot; or \&quot;52.3\&quot;) (optional)
     * @param  string $checkoutMetadata An arbitrary text field that can be used with &lt;a href&#x3D;\&quot;https://support.sendcloud.com/hc/en-us/articles/18580048370705-Checkout-rules\&quot;&gt;Checkout Rules&lt;/a&gt; to control which delivery options are displayed during checkout. For example, you might use it to pass a product SKU, goods category, or any other custom property to show or hide specific delivery options during checkout (optional)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function scPublicV3CheckoutApiGetDeliveryOptionsAsyncWithHttpInfo($configurationId, $weightValue, $totalOrderValue, $fromCountryCode, $toCountryCode, $checkoutIdentifierType = 'shipping_option_code', $toPostalCode = null, $parcelLength = null, $parcelWidth = null, $parcelHeight = null, $checkoutMetadata = null)
    {
        $returnType = '\Toppy\Sendcloud\Model\DeliveryOptionsResponse';
        $request = $this->scPublicV3CheckoutApiGetDeliveryOptionsRequest($configurationId, $weightValue, $totalOrderValue, $fromCountryCode, $toCountryCode, $checkoutIdentifierType, $toPostalCode, $parcelLength, $parcelWidth, $parcelHeight, $checkoutMetadata);

        return $this->httpAsyncClient->sendAsyncRequest($request)
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function (HttpException $exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $exception->getRequest(),
                        $exception->getResponse(),
                        $exception
                    );
                }
            );
    }

    /**
     * Create request for operation 'scPublicV3CheckoutApiGetDeliveryOptions'
     *
     * @param  string $configurationId The unique ID of the checkout configuration used to retrieve delivery options (required)
     * @param  int $weightValue The total weight of the cart or order, specified in grams by default. This parameter is used to select the most suitable shipping option. (required)
     * @param  string $totalOrderValue The total price of the cart or order, specified in the currency of the checkout configuration. This parameter is used to calculate the shipping rate if rates are configured for the delivery method. It can also be used to determine if free shipping is applicable based on the configured pricing rules. (required)
     * @param  mixed $fromCountryCode The sender&#39;s country code for the shipment, formatted as an [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) code (required)
     * @param  mixed $toCountryCode The recipient&#39;s country code for the shipment, formatted as an [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) code (required)
     * @param  string $checkoutIdentifierType Specifies how to retrieve the shipping label. Currently, only the &#x60;shipping_option_code&#x60; type is supported.  When this type is used, the &#x60;checkout_identifier&#x60; field in each delivery option contains the shipping option code, which is required to &lt;a href&#x3D;\&quot;https://api.sendcloud.dev/docs/sendcloud-public-api/shipments/operations/create-a-shipment\&quot;&gt;create a shipment&lt;/a&gt; (optional, default to 'shipping_option_code')
     * @param  string $toPostalCode The recipient&#39;s postal code. Use this in combination with &lt;a href&#x3D;\&quot;https://support.sendcloud.com/hc/en-us/articles/18580048370705-Checkout-rules\&quot;&gt;Checkout Rules&lt;/a&gt; to show or hide delivery options for specific locations. (optional)
     * @param  float $parcelLength The parcel&#39;s length in centimeters (e.g., \&quot;48\&quot; or \&quot;52.3\&quot;) (optional)
     * @param  float $parcelWidth The parcel&#39;s width in centimeters (e.g., \&quot;48\&quot; or \&quot;52.3\&quot;) (optional)
     * @param  float $parcelHeight The parcel&#39;s height in centimeters (e.g., \&quot;48\&quot; or \&quot;52.3\&quot;) (optional)
     * @param  string $checkoutMetadata An arbitrary text field that can be used with &lt;a href&#x3D;\&quot;https://support.sendcloud.com/hc/en-us/articles/18580048370705-Checkout-rules\&quot;&gt;Checkout Rules&lt;/a&gt; to control which delivery options are displayed during checkout. For example, you might use it to pass a product SKU, goods category, or any other custom property to show or hide specific delivery options during checkout (optional)
     *
     * @throws \InvalidArgumentException
     * @return RequestInterface
     */
    public function scPublicV3CheckoutApiGetDeliveryOptionsRequest($configurationId, $weightValue, $totalOrderValue, $fromCountryCode, $toCountryCode, $checkoutIdentifierType = 'shipping_option_code', $toPostalCode = null, $parcelLength = null, $parcelWidth = null, $parcelHeight = null, $checkoutMetadata = null)
    {
        // verify the required parameter 'configurationId' is set
        if ($configurationId === null || (is_array($configurationId) && count($configurationId) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $configurationId when calling scPublicV3CheckoutApiGetDeliveryOptions'
            );
        }
        // verify the required parameter 'weightValue' is set
        if ($weightValue === null || (is_array($weightValue) && count($weightValue) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $weightValue when calling scPublicV3CheckoutApiGetDeliveryOptions'
            );
        }
        if ($weightValue < 1) {
            throw new \InvalidArgumentException('invalid value for "$weightValue" when calling DeliveryOptionsApi.scPublicV3CheckoutApiGetDeliveryOptions, must be bigger than or equal to 1.');
        }

        // verify the required parameter 'totalOrderValue' is set
        if ($totalOrderValue === null || (is_array($totalOrderValue) && count($totalOrderValue) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $totalOrderValue when calling scPublicV3CheckoutApiGetDeliveryOptions'
            );
        }
        if (strlen($totalOrderValue) < 1) {
            throw new \InvalidArgumentException('invalid length for "$totalOrderValue" when calling DeliveryOptionsApi.scPublicV3CheckoutApiGetDeliveryOptions, must be bigger than or equal to 1.');
        }

        // verify the required parameter 'fromCountryCode' is set
        if ($fromCountryCode === null || (is_array($fromCountryCode) && count($fromCountryCode) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $fromCountryCode when calling scPublicV3CheckoutApiGetDeliveryOptions'
            );
        }
        // verify the required parameter 'toCountryCode' is set
        if ($toCountryCode === null || (is_array($toCountryCode) && count($toCountryCode) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $toCountryCode when calling scPublicV3CheckoutApiGetDeliveryOptions'
            );
        }
        if ($toPostalCode !== null && strlen($toPostalCode) > 15) {
            throw new \InvalidArgumentException('invalid length for "$toPostalCode" when calling DeliveryOptionsApi.scPublicV3CheckoutApiGetDeliveryOptions, must be smaller than or equal to 15.');
        }

        if ($checkoutMetadata !== null && strlen($checkoutMetadata) > 128) {
            throw new \InvalidArgumentException('invalid length for "$checkoutMetadata" when calling DeliveryOptionsApi.scPublicV3CheckoutApiGetDeliveryOptions, must be smaller than or equal to 128.');
        }


        $resourcePath = '/checkout/configurations/{configuration_id}/delivery-options';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = null;
        $multipart = false;

        // query params
        if ($weightValue !== null) {
            if('form' === 'form' && is_array($weightValue)) {
                foreach($weightValue as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['weight_value'] = $weightValue;
            }
        }
        // query params
        if ($totalOrderValue !== null) {
            if('form' === 'form' && is_array($totalOrderValue)) {
                foreach($totalOrderValue as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['total_order_value'] = $totalOrderValue;
            }
        }
        // query params
        if ($fromCountryCode !== null) {
            if('form' === 'form' && is_array($fromCountryCode)) {
                foreach($fromCountryCode as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['from_country_code'] = $fromCountryCode;
            }
        }
        // query params
        if ($toCountryCode !== null) {
            if('form' === 'form' && is_array($toCountryCode)) {
                foreach($toCountryCode as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['to_country_code'] = $toCountryCode;
            }
        }
        // query params
        if ($checkoutIdentifierType !== null) {
            if('form' === 'form' && is_array($checkoutIdentifierType)) {
                foreach($checkoutIdentifierType as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['checkout_identifier_type'] = $checkoutIdentifierType;
            }
        }
        // query params
        if ($toPostalCode !== null) {
            if('form' === 'form' && is_array($toPostalCode)) {
                foreach($toPostalCode as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['to_postal_code'] = $toPostalCode;
            }
        }
        // query params
        if ($parcelLength !== null) {
            if('form' === 'form' && is_array($parcelLength)) {
                foreach($parcelLength as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['parcel_length'] = $parcelLength;
            }
        }
        // query params
        if ($parcelWidth !== null) {
            if('form' === 'form' && is_array($parcelWidth)) {
                foreach($parcelWidth as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['parcel_width'] = $parcelWidth;
            }
        }
        // query params
        if ($parcelHeight !== null) {
            if('form' === 'form' && is_array($parcelHeight)) {
                foreach($parcelHeight as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['parcel_height'] = $parcelHeight;
            }
        }
        // query params
        if ($checkoutMetadata !== null) {
            if('form' === 'form' && is_array($checkoutMetadata)) {
                foreach($checkoutMetadata as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['checkout_metadata'] = $checkoutMetadata;
            }
        }


        // path params
        if ($configurationId !== null) {
            $resourcePath = str_replace(
                '{' . 'configuration_id' . '}',
                ObjectSerializer::toPathValue($configurationId),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            '',
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($this->headerSelector->isJsonMime($headers['Content-Type'])) {
                $httpBody = json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();

        $uri = $this->createUri($operationHost, $resourcePath, $queryParams);

        return $this->createRequest('GET', $uri, $headers, $httpBody);
    }


    /**
     * @param string $method
     * @param string|UriInterface $uri
     * @param array $headers
     * @param string|StreamInterface|null $body
     *
     * @return RequestInterface
     */
    protected function createRequest(string $method, $uri, array $headers = [], $body = null): RequestInterface
    {
        if ($this->requestFactory instanceof RequestFactory) {
            return $this->requestFactory->createRequest(
                $method,
                $uri,
                $headers,
                $body
            );
        }

        if (is_string($body) && '' !== $body && null === $this->streamFactory) {
            throw new \RuntimeException('Cannot create request: A stream factory is required to create a request with a non-empty string body.');
        }

        $request = $this->requestFactory->createRequest($method, $uri);

        foreach ($headers as $key => $value) {
            $request = $request->withHeader($key, $value);
        }

        if (null !== $body && '' !== $body) {
            $request = $request->withBody(
                is_string($body) ? $this->streamFactory->createStream($body) : $body
            );
        }

        return $request;
    }

    private function createUri(
        string $operationHost,
        string $resourcePath,
        array $queryParams
    ): UriInterface {
        $parsedUrl = parse_url($operationHost);

        $host = $parsedUrl['host'] ?? null;
        $scheme = $parsedUrl['scheme'] ?? null;
        $basePath = $parsedUrl['path'] ?? null;
        $port = $parsedUrl['port'] ?? null;
        $user = $parsedUrl['user'] ?? null;
        $password = $parsedUrl['pass'] ?? null;

        $uri = $this->uriFactory->createUri($basePath . $resourcePath)
            ->withHost($host)
            ->withScheme($scheme)
            ->withPort($port)
            ->withQuery(ObjectSerializer::buildQuery($queryParams));

        if ($user) {
            $uri = $uri->withUserInfo($user, $password);
        }

        return $uri;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
			$request,
                        $response,
                        $exception
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
