<?php

declare(strict_types=1);

/**
 * ParcelTrackingApi
 * PHP version 7.2
 *
 * @category Class
 * @package  Toppy\Sendcloud
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
/**
 * Sendcloud Public REST API
 *
 * Complete Sendcloud API v3 specification - merged from official sendcloud.dev documentation
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: contact@sendcloud.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.18.0
 */
/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
namespace Toppy\Sendcloud\Api;

use GuzzleHttp\Psr7\MultipartStream;
use Http\Client\Common\Plugin\ErrorPlugin;
use Http\Client\Common\Plugin\RedirectPlugin;
use Http\Client\Common\PluginClient;
use Http\Client\Common\PluginClientFactory;
use Http\Client\Exception\HttpException;
use Http\Client\HttpAsyncClient;
use Http\Discovery\HttpAsyncClientDiscovery;
use Http\Discovery\Psr17FactoryDiscovery;
use Http\Discovery\Psr18ClientDiscovery;
use Http\Message\RequestFactory;
use Http\Promise\Promise;
use Toppy\Sendcloud\ApiException;
use Toppy\Sendcloud\Configuration;
use Toppy\Sendcloud\DebugPlugin;
use Toppy\Sendcloud\HeaderSelector;
use Toppy\Sendcloud\FormDataProcessor;
use Toppy\Sendcloud\ObjectSerializer;
use Psr\Http\Client\ClientExceptionInterface;
use Psr\Http\Client\ClientInterface;
use Psr\Http\Message\RequestFactoryInterface;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use Psr\Http\Message\StreamFactoryInterface;
use Psr\Http\Message\UriFactoryInterface;
use Psr\Http\Message\UriInterface;
use function sprintf;

/**
 * ParcelTrackingApi Class Doc Comment
 *
 * @category Class
 * @package  Toppy\Sendcloud
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ParcelTrackingApi
{
    /**
     * @var PluginClient
     */
    protected $httpClient;

    /**
     * @var PluginClient
     */
    protected $httpAsyncClient;

    /**
     * @var UriFactoryInterface
     */
    protected $uriFactory;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var RequestFactoryInterface
     */
    protected $requestFactory;

    /**
     * @var StreamFactoryInterface
     */
    protected $streamFactory;

    /**
     * @param int $hostIndex
     */
    public function __construct(
        ?ClientInterface $httpClient = null,
        ?Configuration $configuration = null,
        ?HttpAsyncClient $httpAsyncClient = null,
        ?UriFactoryInterface $uriFactory = null,
        ?RequestFactoryInterface $requestFactory = null,
        ?StreamFactoryInterface $streamFactory = null,
        protected ?HeaderSelector $headerSelector = new HeaderSelector(),
        ?array $plugins = null,
        /**
         * @var int Host index
         */
        protected $hostIndex = 0
    ) {
        $this->config = $configuration ?? (new Configuration())->setHost('https://account.sendcloud.com');
        $this->requestFactory = $requestFactory ?? Psr17FactoryDiscovery::findRequestFactory();
        $this->streamFactory = $streamFactory ?? Psr17FactoryDiscovery::findStreamFactory();

        $plugins = $plugins ?? [
            new RedirectPlugin(['strict' => true]),
            new ErrorPlugin(),
        ];

        if ($this->config->getDebug()) {
            $plugins[] = new DebugPlugin(fopen($this->config->getDebugFile(), 'ab'));
        }

        $this->httpClient = (new PluginClientFactory())->createClient(
            $httpClient ?? Psr18ClientDiscovery::find(),
            $plugins
        );

        $this->httpAsyncClient = (new PluginClientFactory())->createClient(
            $httpAsyncClient ?? HttpAsyncClientDiscovery::find(),
            $plugins
        );

        $this->uriFactory = $uriFactory ?? Psr17FactoryDiscovery::findUriFactory();
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation scPublicV3ShippingIntelligenceEngineGetGetParcelByTrackingNumber
     *
     * Retrieve tracking information for a parcel
     *
     * @param  string $trackingNumber Parcel tracking number (required)
     *
     * @throws \Toppy\Sendcloud\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Toppy\Sendcloud\Model\ParcelTrackingResponse|\Toppy\Sendcloud\Model\ScPublicV3ShippingIntelligenceEngineGetGetParcelByTrackingNumber404Response|\Toppy\Sendcloud\Model\HTTPValidationError
     */
    public function scPublicV3ShippingIntelligenceEngineGetGetParcelByTrackingNumber($trackingNumber)
    {
        [$response] = $this->scPublicV3ShippingIntelligenceEngineGetGetParcelByTrackingNumberWithHttpInfo($trackingNumber);
        return $response;
    }

    /**
     * Operation scPublicV3ShippingIntelligenceEngineGetGetParcelByTrackingNumberWithHttpInfo
     *
     * Retrieve tracking information for a parcel
     *
     * @param  string $trackingNumber Parcel tracking number (required)
     *
     * @throws \Toppy\Sendcloud\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Toppy\Sendcloud\Model\ParcelTrackingResponse|\Toppy\Sendcloud\Model\ScPublicV3ShippingIntelligenceEngineGetGetParcelByTrackingNumber404Response|\Toppy\Sendcloud\Model\HTTPValidationError, HTTP status code, HTTP response headers (array of strings)
     */
    public function scPublicV3ShippingIntelligenceEngineGetGetParcelByTrackingNumberWithHttpInfo($trackingNumber)
    {
        $request = $this->scPublicV3ShippingIntelligenceEngineGetGetParcelByTrackingNumberRequest($trackingNumber);

        try {
            try {
                $response = $this->httpClient->sendRequest($request);
            } catch (HttpException $e) {
                $response = $e->getResponse();
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $response->getStatusCode(),
                        (string) $request->getUri()
                    ),
                    $request,
                    $response,
                    $e
                );
            } catch (ClientExceptionInterface $e) {
                throw new ApiException(
                    sprintf('[%d] %s', $e->getCode(), $e->getMessage()),
                    $request,
                    null,
                    $e
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        \Toppy\Sendcloud\Model\ParcelTrackingResponse::class,
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        \Toppy\Sendcloud\Model\ScPublicV3ShippingIntelligenceEngineGetGetParcelByTrackingNumber404Response::class,
                        $request,
                        $response,
                    );
                case 422:
                    return $this->handleResponseWithDataType(
                        \Toppy\Sendcloud\Model\HTTPValidationError::class,
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $request,
                    $response
                );
            }

            return $this->handleResponseWithDataType(
                \Toppy\Sendcloud\Model\ParcelTrackingResponse::class,
                $request,
                $response,
            );
        } catch (ApiException $apiException) {
            switch ($apiException->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $apiException->getResponseBody(),
                        \Toppy\Sendcloud\Model\ParcelTrackingResponse::class,
                        $apiException->getResponseHeaders()
                    );
                    $apiException->setResponseObject($data);
                    throw $apiException;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $apiException->getResponseBody(),
                        \Toppy\Sendcloud\Model\ScPublicV3ShippingIntelligenceEngineGetGetParcelByTrackingNumber404Response::class,
                        $apiException->getResponseHeaders()
                    );
                    $apiException->setResponseObject($data);
                    throw $apiException;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $apiException->getResponseBody(),
                        \Toppy\Sendcloud\Model\HTTPValidationError::class,
                        $apiException->getResponseHeaders()
                    );
                    $apiException->setResponseObject($data);
                    throw $apiException;
            }
        

            throw $apiException;
        }
    }

    /**
     * Operation scPublicV3ShippingIntelligenceEngineGetGetParcelByTrackingNumberAsync
     *
     * Retrieve tracking information for a parcel
     *
     * @param  string $trackingNumber Parcel tracking number (required)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function scPublicV3ShippingIntelligenceEngineGetGetParcelByTrackingNumberAsync($trackingNumber)
    {
        return $this->scPublicV3ShippingIntelligenceEngineGetGetParcelByTrackingNumberAsyncWithHttpInfo($trackingNumber)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation scPublicV3ShippingIntelligenceEngineGetGetParcelByTrackingNumberAsyncWithHttpInfo
     *
     * Retrieve tracking information for a parcel
     *
     * @param  string $trackingNumber Parcel tracking number (required)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function scPublicV3ShippingIntelligenceEngineGetGetParcelByTrackingNumberAsyncWithHttpInfo($trackingNumber)
    {
        $returnType = \Toppy\Sendcloud\Model\ParcelTrackingResponse::class;
        $request = $this->scPublicV3ShippingIntelligenceEngineGetGetParcelByTrackingNumberRequest($trackingNumber);

        return $this->httpAsyncClient->sendAsyncRequest($request)
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function (HttpException $httpException) {
                    $response = $httpException->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $httpException->getRequest()->getUri()
                        ),
                        $httpException->getRequest(),
                        $httpException->getResponse(),
                        $httpException
                    );
                }
            );
    }

    /**
     * Create request for operation 'scPublicV3ShippingIntelligenceEngineGetGetParcelByTrackingNumber'
     *
     * @param  string $trackingNumber Parcel tracking number (required)
     *
     * @throws \InvalidArgumentException
     * @return RequestInterface
     */
    public function scPublicV3ShippingIntelligenceEngineGetGetParcelByTrackingNumberRequest($trackingNumber)
    {
        // verify the required parameter 'trackingNumber' is set
        if ($trackingNumber === null || (is_array($trackingNumber) && $trackingNumber === [])) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $trackingNumber when calling scPublicV3ShippingIntelligenceEngineGetGetParcelByTrackingNumber'
            );
        }

        if (strlen($trackingNumber) > 255) {
            throw new \InvalidArgumentException('invalid length for "$trackingNumber" when calling ParcelTrackingApi.scPublicV3ShippingIntelligenceEngineGetGetParcelByTrackingNumber, must be smaller than or equal to 255.');
        }

        if (strlen($trackingNumber) < 1) {
            throw new \InvalidArgumentException('invalid length for "$trackingNumber" when calling ParcelTrackingApi.scPublicV3ShippingIntelligenceEngineGetGetParcelByTrackingNumber, must be bigger than or equal to 1.');
        }


        $resourcePath = '/parcels/tracking/{tracking_number}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = null;
        $multipart = false;



        // path params
        $resourcePath = str_replace(
            '{tracking_number}',
            ObjectSerializer::toPathValue($trackingNumber),
            $resourcePath
        );


        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            '',
            $multipart
        );

        // for model (json/xml)
        if ($formParams !== []) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }

                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($this->headerSelector->isJsonMime($headers['Content-Type'])) {
                $httpBody = json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();

        $uri = $this->createUri($operationHost, $resourcePath, $queryParams);

        return $this->createRequest('GET', $uri, $headers, $httpBody);
    }

    /**
     * Operation scPublicV3ShippingIntelligenceEnginePostRegisterParcelForTracking
     *
     * Create a tracking-only parcel
     *
     * @param  \Toppy\Sendcloud\Model\ParcelTrackingCreateRequest $parcelTrackingCreateRequest parcelTrackingCreateRequest (required)
     *
     * @throws \Toppy\Sendcloud\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Toppy\Sendcloud\Model\ParcelTrackingCreateResponse|\Toppy\Sendcloud\Model\ScPublicV3ShippingIntelligenceEnginePostRegisterParcelForTracking409Response|\Toppy\Sendcloud\Model\HTTPValidationError
     */
    public function scPublicV3ShippingIntelligenceEnginePostRegisterParcelForTracking($parcelTrackingCreateRequest)
    {
        [$response] = $this->scPublicV3ShippingIntelligenceEnginePostRegisterParcelForTrackingWithHttpInfo($parcelTrackingCreateRequest);
        return $response;
    }

    /**
     * Operation scPublicV3ShippingIntelligenceEnginePostRegisterParcelForTrackingWithHttpInfo
     *
     * Create a tracking-only parcel
     *
     * @param  \Toppy\Sendcloud\Model\ParcelTrackingCreateRequest $parcelTrackingCreateRequest (required)
     *
     * @throws \Toppy\Sendcloud\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Toppy\Sendcloud\Model\ParcelTrackingCreateResponse|\Toppy\Sendcloud\Model\ScPublicV3ShippingIntelligenceEnginePostRegisterParcelForTracking409Response|\Toppy\Sendcloud\Model\HTTPValidationError, HTTP status code, HTTP response headers (array of strings)
     */
    public function scPublicV3ShippingIntelligenceEnginePostRegisterParcelForTrackingWithHttpInfo($parcelTrackingCreateRequest)
    {
        $request = $this->scPublicV3ShippingIntelligenceEnginePostRegisterParcelForTrackingRequest($parcelTrackingCreateRequest);

        try {
            try {
                $response = $this->httpClient->sendRequest($request);
            } catch (HttpException $e) {
                $response = $e->getResponse();
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $response->getStatusCode(),
                        (string) $request->getUri()
                    ),
                    $request,
                    $response,
                    $e
                );
            } catch (ClientExceptionInterface $e) {
                throw new ApiException(
                    sprintf('[%d] %s', $e->getCode(), $e->getMessage()),
                    $request,
                    null,
                    $e
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        \Toppy\Sendcloud\Model\ParcelTrackingCreateResponse::class,
                        $request,
                        $response,
                    );
                case 409:
                    return $this->handleResponseWithDataType(
                        \Toppy\Sendcloud\Model\ScPublicV3ShippingIntelligenceEnginePostRegisterParcelForTracking409Response::class,
                        $request,
                        $response,
                    );
                case 422:
                    return $this->handleResponseWithDataType(
                        \Toppy\Sendcloud\Model\HTTPValidationError::class,
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $request,
                    $response
                );
            }

            return $this->handleResponseWithDataType(
                \Toppy\Sendcloud\Model\ParcelTrackingCreateResponse::class,
                $request,
                $response,
            );
        } catch (ApiException $apiException) {
            switch ($apiException->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $apiException->getResponseBody(),
                        \Toppy\Sendcloud\Model\ParcelTrackingCreateResponse::class,
                        $apiException->getResponseHeaders()
                    );
                    $apiException->setResponseObject($data);
                    throw $apiException;
                case 409:
                    $data = ObjectSerializer::deserialize(
                        $apiException->getResponseBody(),
                        \Toppy\Sendcloud\Model\ScPublicV3ShippingIntelligenceEnginePostRegisterParcelForTracking409Response::class,
                        $apiException->getResponseHeaders()
                    );
                    $apiException->setResponseObject($data);
                    throw $apiException;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $apiException->getResponseBody(),
                        \Toppy\Sendcloud\Model\HTTPValidationError::class,
                        $apiException->getResponseHeaders()
                    );
                    $apiException->setResponseObject($data);
                    throw $apiException;
            }
        

            throw $apiException;
        }
    }

    /**
     * Operation scPublicV3ShippingIntelligenceEnginePostRegisterParcelForTrackingAsync
     *
     * Create a tracking-only parcel
     *
     * @param  \Toppy\Sendcloud\Model\ParcelTrackingCreateRequest $parcelTrackingCreateRequest (required)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function scPublicV3ShippingIntelligenceEnginePostRegisterParcelForTrackingAsync($parcelTrackingCreateRequest)
    {
        return $this->scPublicV3ShippingIntelligenceEnginePostRegisterParcelForTrackingAsyncWithHttpInfo($parcelTrackingCreateRequest)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation scPublicV3ShippingIntelligenceEnginePostRegisterParcelForTrackingAsyncWithHttpInfo
     *
     * Create a tracking-only parcel
     *
     * @param  \Toppy\Sendcloud\Model\ParcelTrackingCreateRequest $parcelTrackingCreateRequest (required)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function scPublicV3ShippingIntelligenceEnginePostRegisterParcelForTrackingAsyncWithHttpInfo($parcelTrackingCreateRequest)
    {
        $returnType = \Toppy\Sendcloud\Model\ParcelTrackingCreateResponse::class;
        $request = $this->scPublicV3ShippingIntelligenceEnginePostRegisterParcelForTrackingRequest($parcelTrackingCreateRequest);

        return $this->httpAsyncClient->sendAsyncRequest($request)
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function (HttpException $httpException) {
                    $response = $httpException->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $httpException->getRequest()->getUri()
                        ),
                        $httpException->getRequest(),
                        $httpException->getResponse(),
                        $httpException
                    );
                }
            );
    }

    /**
     * Create request for operation 'scPublicV3ShippingIntelligenceEnginePostRegisterParcelForTracking'
     *
     * @param  \Toppy\Sendcloud\Model\ParcelTrackingCreateRequest $parcelTrackingCreateRequest (required)
     *
     * @throws \InvalidArgumentException
     * @return RequestInterface
     */
    public function scPublicV3ShippingIntelligenceEnginePostRegisterParcelForTrackingRequest($parcelTrackingCreateRequest)
    {
        // verify the required parameter 'parcelTrackingCreateRequest' is set
        if ($parcelTrackingCreateRequest === null || (is_array($parcelTrackingCreateRequest) && $parcelTrackingCreateRequest === [])) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $parcelTrackingCreateRequest when calling scPublicV3ShippingIntelligenceEnginePostRegisterParcelForTracking'
            );
        }

        $resourcePath = '/parcels/tracking';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = null;
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            'application/json',
            $multipart
        );

        // for model (json/xml)
        if (isset($parcelTrackingCreateRequest)) {
            if ($this->headerSelector->isJsonMime($headers['Content-Type'])) {
                $httpBody = json_encode(ObjectSerializer::sanitizeForSerialization($parcelTrackingCreateRequest));
            } else {
                $httpBody = $parcelTrackingCreateRequest;
            }
        } elseif ($formParams !== []) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }

                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($this->headerSelector->isJsonMime($headers['Content-Type'])) {
                $httpBody = json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();

        $uri = $this->createUri($operationHost, $resourcePath, $queryParams);

        return $this->createRequest('POST', $uri, $headers, $httpBody);
    }


    /**
     * @param string|UriInterface $uri
     * @param string[] $headers
     * @param string|StreamInterface|null $body
     *
     */
    protected function createRequest(string $method, $uri, array $headers = [], $body = null): RequestInterface
    {
        if ($this->requestFactory instanceof RequestFactory) {
            return $this->requestFactory->createRequest(
                $method,
                $uri,
                $headers,
                $body
            );
        }

        if (is_string($body) && '' !== $body && null === $this->streamFactory) {
            throw new \RuntimeException('Cannot create request: A stream factory is required to create a request with a non-empty string body.');
        }

        $request = $this->requestFactory->createRequest($method, $uri);

        foreach ($headers as $key => $value) {
            $request = $request->withHeader($key, $value);
        }

        if (null !== $body && '' !== $body) {
            return $request->withBody(
                is_string($body) ? $this->streamFactory->createStream($body) : $body
            );
        }

        return $request;
    }

    private function createUri(
        string $operationHost,
        string $resourcePath,
        array $queryParams
    ): UriInterface {
        $parsedUrl = parse_url($operationHost);

        $host = $parsedUrl['host'] ?? null;
        $scheme = $parsedUrl['scheme'] ?? null;
        $basePath = $parsedUrl['path'] ?? null;
        $port = $parsedUrl['port'] ?? null;
        $user = $parsedUrl['user'] ?? null;
        $password = $parsedUrl['pass'] ?? null;

        $uri = $this->uriFactory->createUri($basePath . $resourcePath)
            ->withHost($host)
            ->withScheme($scheme)
            ->withPort($port)
            ->withQuery(ObjectSerializer::buildQuery($queryParams));

        if ($user) {
            return $uri->withUserInfo($user, $password);
        }

        return $uri;
    }

    /**
     * @return array<int, object|int|mixed[]|null>
     */
    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
			$request,
                        $response,
                        $exception
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }
}
