<?php

declare(strict_types=1);

/**
 * ReturnsApi
 * PHP version 7.2
 *
 * @category Class
 * @package  Toppy\Sendcloud\V3
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
/**
 * Sendcloud Public REST API
 *
 * Complete Sendcloud API v3 specification - merged from official sendcloud.dev documentation
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: contact@sendcloud.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.18.0
 */
/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
namespace Toppy\Sendcloud\V3\Api;

use GuzzleHttp\Psr7\MultipartStream;
use Http\Client\Common\Plugin\ErrorPlugin;
use Http\Client\Common\Plugin\RedirectPlugin;
use Http\Client\Common\PluginClient;
use Http\Client\Common\PluginClientFactory;
use Http\Client\Exception\HttpException;
use Http\Client\HttpAsyncClient;
use Http\Discovery\HttpAsyncClientDiscovery;
use Http\Discovery\Psr17FactoryDiscovery;
use Http\Discovery\Psr18ClientDiscovery;
use Http\Message\RequestFactory;
use Http\Promise\Promise;
use Toppy\Sendcloud\V3\ApiException;
use Toppy\Sendcloud\V3\Configuration;
use Toppy\Sendcloud\V3\DebugPlugin;
use Toppy\Sendcloud\V3\HeaderSelector;
use Toppy\Sendcloud\V3\FormDataProcessor;
use Toppy\Sendcloud\V3\ObjectSerializer;
use Psr\Http\Client\ClientExceptionInterface;
use Psr\Http\Client\ClientInterface;
use Psr\Http\Message\RequestFactoryInterface;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use Psr\Http\Message\StreamFactoryInterface;
use Psr\Http\Message\UriFactoryInterface;
use Psr\Http\Message\UriInterface;
use function sprintf;

/**
 * ReturnsApi Class Doc Comment
 *
 * @category Class
 * @package  Toppy\Sendcloud\V3
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ReturnsApi
{
    /**
     * @var PluginClient
     */
    protected $httpClient;

    /**
     * @var PluginClient
     */
    protected $httpAsyncClient;

    /**
     * @var UriFactoryInterface
     */
    protected $uriFactory;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var RequestFactoryInterface
     */
    protected $requestFactory;

    /**
     * @var StreamFactoryInterface
     */
    protected $streamFactory;

    /**
     * @param int $hostIndex
     */
    public function __construct(
        ?ClientInterface $httpClient = null,
        ?Configuration $configuration = null,
        ?HttpAsyncClient $httpAsyncClient = null,
        ?UriFactoryInterface $uriFactory = null,
        ?RequestFactoryInterface $requestFactory = null,
        ?StreamFactoryInterface $streamFactory = null,
        protected ?HeaderSelector $headerSelector = new HeaderSelector(),
        ?array $plugins = null,
        /**
         * @var int Host index
         */
        protected $hostIndex = 0
    ) {
        $this->config = $configuration ?? (new Configuration())->setHost('https://panel.sendcloud.sc/api/v3');
        $this->requestFactory = $requestFactory ?? Psr17FactoryDiscovery::findRequestFactory();
        $this->streamFactory = $streamFactory ?? Psr17FactoryDiscovery::findStreamFactory();

        $plugins = $plugins ?? [
            new RedirectPlugin(['strict' => true]),
            new ErrorPlugin(),
        ];

        if ($this->config->getDebug()) {
            $plugins[] = new DebugPlugin(fopen($this->config->getDebugFile(), 'ab'));
        }

        $this->httpClient = (new PluginClientFactory())->createClient(
            $httpClient ?? Psr18ClientDiscovery::find(),
            $plugins
        );

        $this->httpAsyncClient = (new PluginClientFactory())->createClient(
            $httpAsyncClient ?? HttpAsyncClientDiscovery::find(),
            $plugins
        );

        $this->uriFactory = $uriFactory ?? Psr17FactoryDiscovery::findUriFactory();
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation scPublicV3ScpGetReturnsGetDetails
     *
     * Retrieve a return
     *
     * @param  int $id The internal Sendcloud id of this return (required)
     *
     * @throws \Toppy\Sendcloud\V3\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Toppy\Sendcloud\V3\Model\ModelReturn
     */
    public function scPublicV3ScpGetReturnsGetDetails($id)
    {
        [$response] = $this->scPublicV3ScpGetReturnsGetDetailsWithHttpInfo($id);
        return $response;
    }

    /**
     * Operation scPublicV3ScpGetReturnsGetDetailsWithHttpInfo
     *
     * Retrieve a return
     *
     * @param  int $id The internal Sendcloud id of this return (required)
     *
     * @throws \Toppy\Sendcloud\V3\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Toppy\Sendcloud\V3\Model\ModelReturn, HTTP status code, HTTP response headers (array of strings)
     */
    public function scPublicV3ScpGetReturnsGetDetailsWithHttpInfo($id)
    {
        $request = $this->scPublicV3ScpGetReturnsGetDetailsRequest($id);

        try {
            try {
                $response = $this->httpClient->sendRequest($request);
            } catch (HttpException $e) {
                $response = $e->getResponse();
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $response->getStatusCode(),
                        (string) $request->getUri()
                    ),
                    $request,
                    $response,
                    $e
                );
            } catch (ClientExceptionInterface $e) {
                throw new ApiException(
                    sprintf('[%d] %s', $e->getCode(), $e->getMessage()),
                    $request,
                    null,
                    $e
                );
            }

            $statusCode = $response->getStatusCode();


            if ($statusCode === 200) {
                return $this->handleResponseWithDataType(
                    \Toppy\Sendcloud\V3\Model\ModelReturn::class,
                    $request,
                    $response,
                );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $request,
                    $response
                );
            }

            return $this->handleResponseWithDataType(
                \Toppy\Sendcloud\V3\Model\ModelReturn::class,
                $request,
                $response,
            );
        } catch (ApiException $apiException) {
            if ($apiException->getCode() === 200) {
                $data = ObjectSerializer::deserialize(
                    $apiException->getResponseBody(),
                    \Toppy\Sendcloud\V3\Model\ModelReturn::class,
                    $apiException->getResponseHeaders()
                );
                $apiException->setResponseObject($data);
                throw $apiException;
            }
        

            throw $apiException;
        }
    }

    /**
     * Operation scPublicV3ScpGetReturnsGetDetailsAsync
     *
     * Retrieve a return
     *
     * @param  int $id The internal Sendcloud id of this return (required)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function scPublicV3ScpGetReturnsGetDetailsAsync($id)
    {
        return $this->scPublicV3ScpGetReturnsGetDetailsAsyncWithHttpInfo($id)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation scPublicV3ScpGetReturnsGetDetailsAsyncWithHttpInfo
     *
     * Retrieve a return
     *
     * @param  int $id The internal Sendcloud id of this return (required)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function scPublicV3ScpGetReturnsGetDetailsAsyncWithHttpInfo($id)
    {
        $returnType = \Toppy\Sendcloud\V3\Model\ModelReturn::class;
        $request = $this->scPublicV3ScpGetReturnsGetDetailsRequest($id);

        return $this->httpAsyncClient->sendAsyncRequest($request)
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function (HttpException $httpException) {
                    $response = $httpException->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $httpException->getRequest()->getUri()
                        ),
                        $httpException->getRequest(),
                        $httpException->getResponse(),
                        $httpException
                    );
                }
            );
    }

    /**
     * Create request for operation 'scPublicV3ScpGetReturnsGetDetails'
     *
     * @param  int $id The internal Sendcloud id of this return (required)
     *
     * @throws \InvalidArgumentException
     * @return RequestInterface
     */
    public function scPublicV3ScpGetReturnsGetDetailsRequest($id)
    {
        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && $id === [])) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling scPublicV3ScpGetReturnsGetDetails'
            );
        }

        $resourcePath = '/returns/{id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = null;
        $multipart = false;



        // path params
        $resourcePath = str_replace(
            '{id}',
            ObjectSerializer::toPathValue($id),
            $resourcePath
        );


        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            '',
            $multipart
        );

        // for model (json/xml)
        if ($formParams !== []) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }

                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($this->headerSelector->isJsonMime($headers['Content-Type'])) {
                $httpBody = json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();

        $uri = $this->createUri($operationHost, $resourcePath, $queryParams);

        return $this->createRequest('GET', $uri, $headers, $httpBody);
    }

    /**
     * Operation scPublicV3ScpGetReturnsGetReturns
     *
     * Retrieve a list of returns
     *
     * @param  string $fromDate Excludes all returns before this datetime (required)
     * @param  string $toDate Excludes all returns after this datetime (required)
     * @param  string $parentParcelStatus Search for returns with this parent status (optional)
     * @param  float $pageSize Refers to the number of items per page (optional)
     *
     * @throws \Toppy\Sendcloud\V3\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Toppy\Sendcloud\V3\Model\ScPublicV3ScpGetReturnsGetReturns200Response
     */
    public function scPublicV3ScpGetReturnsGetReturns($fromDate, $toDate, $parentParcelStatus = null, $pageSize = null)
    {
        [$response] = $this->scPublicV3ScpGetReturnsGetReturnsWithHttpInfo($fromDate, $toDate, $parentParcelStatus, $pageSize);
        return $response;
    }

    /**
     * Operation scPublicV3ScpGetReturnsGetReturnsWithHttpInfo
     *
     * Retrieve a list of returns
     *
     * @param  string $fromDate Excludes all returns before this datetime (required)
     * @param  string $toDate Excludes all returns after this datetime (required)
     * @param  string $parentParcelStatus Search for returns with this parent status (optional)
     * @param  float $pageSize Refers to the number of items per page (optional)
     *
     * @throws \Toppy\Sendcloud\V3\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Toppy\Sendcloud\V3\Model\ScPublicV3ScpGetReturnsGetReturns200Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function scPublicV3ScpGetReturnsGetReturnsWithHttpInfo($fromDate, $toDate, $parentParcelStatus = null, $pageSize = null)
    {
        $request = $this->scPublicV3ScpGetReturnsGetReturnsRequest($fromDate, $toDate, $parentParcelStatus, $pageSize);

        try {
            try {
                $response = $this->httpClient->sendRequest($request);
            } catch (HttpException $e) {
                $response = $e->getResponse();
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $response->getStatusCode(),
                        (string) $request->getUri()
                    ),
                    $request,
                    $response,
                    $e
                );
            } catch (ClientExceptionInterface $e) {
                throw new ApiException(
                    sprintf('[%d] %s', $e->getCode(), $e->getMessage()),
                    $request,
                    null,
                    $e
                );
            }

            $statusCode = $response->getStatusCode();


            if ($statusCode === 200) {
                return $this->handleResponseWithDataType(
                    \Toppy\Sendcloud\V3\Model\ScPublicV3ScpGetReturnsGetReturns200Response::class,
                    $request,
                    $response,
                );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $request,
                    $response
                );
            }

            return $this->handleResponseWithDataType(
                \Toppy\Sendcloud\V3\Model\ScPublicV3ScpGetReturnsGetReturns200Response::class,
                $request,
                $response,
            );
        } catch (ApiException $apiException) {
            if ($apiException->getCode() === 200) {
                $data = ObjectSerializer::deserialize(
                    $apiException->getResponseBody(),
                    \Toppy\Sendcloud\V3\Model\ScPublicV3ScpGetReturnsGetReturns200Response::class,
                    $apiException->getResponseHeaders()
                );
                $apiException->setResponseObject($data);
                throw $apiException;
            }
        

            throw $apiException;
        }
    }

    /**
     * Operation scPublicV3ScpGetReturnsGetReturnsAsync
     *
     * Retrieve a list of returns
     *
     * @param  string $fromDate Excludes all returns before this datetime (required)
     * @param  string $toDate Excludes all returns after this datetime (required)
     * @param  string $parentParcelStatus Search for returns with this parent status (optional)
     * @param  float $pageSize Refers to the number of items per page (optional)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function scPublicV3ScpGetReturnsGetReturnsAsync($fromDate, $toDate, $parentParcelStatus = null, $pageSize = null)
    {
        return $this->scPublicV3ScpGetReturnsGetReturnsAsyncWithHttpInfo($fromDate, $toDate, $parentParcelStatus, $pageSize)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation scPublicV3ScpGetReturnsGetReturnsAsyncWithHttpInfo
     *
     * Retrieve a list of returns
     *
     * @param  string $fromDate Excludes all returns before this datetime (required)
     * @param  string $toDate Excludes all returns after this datetime (required)
     * @param  string $parentParcelStatus Search for returns with this parent status (optional)
     * @param  float $pageSize Refers to the number of items per page (optional)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function scPublicV3ScpGetReturnsGetReturnsAsyncWithHttpInfo($fromDate, $toDate, $parentParcelStatus = null, $pageSize = null)
    {
        $returnType = \Toppy\Sendcloud\V3\Model\ScPublicV3ScpGetReturnsGetReturns200Response::class;
        $request = $this->scPublicV3ScpGetReturnsGetReturnsRequest($fromDate, $toDate, $parentParcelStatus, $pageSize);

        return $this->httpAsyncClient->sendAsyncRequest($request)
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function (HttpException $httpException) {
                    $response = $httpException->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $httpException->getRequest()->getUri()
                        ),
                        $httpException->getRequest(),
                        $httpException->getResponse(),
                        $httpException
                    );
                }
            );
    }

    /**
     * Create request for operation 'scPublicV3ScpGetReturnsGetReturns'
     *
     * @param  string $fromDate Excludes all returns before this datetime (required)
     * @param  string $toDate Excludes all returns after this datetime (required)
     * @param  string $parentParcelStatus Search for returns with this parent status (optional)
     * @param  float $pageSize Refers to the number of items per page (optional)
     *
     * @throws \InvalidArgumentException
     * @return RequestInterface
     */
    public function scPublicV3ScpGetReturnsGetReturnsRequest($fromDate, $toDate, $parentParcelStatus = null, $pageSize = null)
    {
        // verify the required parameter 'fromDate' is set
        if ($fromDate === null || (is_array($fromDate) && $fromDate === [])) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $fromDate when calling scPublicV3ScpGetReturnsGetReturns'
            );
        }

        // verify the required parameter 'toDate' is set
        if ($toDate === null || (is_array($toDate) && $toDate === [])) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $toDate when calling scPublicV3ScpGetReturnsGetReturns'
            );
        }

        if ($pageSize !== null && $pageSize > 40) {
            throw new \InvalidArgumentException('invalid value for "$pageSize" when calling ReturnsApi.scPublicV3ScpGetReturnsGetReturns, must be smaller than or equal to 40.');
        }

        if ($pageSize !== null && $pageSize < 1) {
            throw new \InvalidArgumentException('invalid value for "$pageSize" when calling ReturnsApi.scPublicV3ScpGetReturnsGetReturns, must be bigger than or equal to 1.');
        }


        $resourcePath = '/returns';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = null;
        $multipart = false;
        // query params
        if(is_array($fromDate)) {
            foreach($fromDate as $key => $value) {
                $queryParams[$key] = $value;
            }
        }
        else {
            $queryParams['from_date'] = $fromDate;
        }

        // query params
        if(is_array($toDate)) {
            foreach($toDate as $key => $value) {
                $queryParams[$key] = $value;
            }
        }
        else {
            $queryParams['to_date'] = $toDate;
        }

        // query params
        if ($parentParcelStatus !== null) {
            if(is_array($parentParcelStatus)) {
                foreach($parentParcelStatus as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['parent_parcel_status'] = $parentParcelStatus;
            }
        }

        // query params
        if ($pageSize !== null) {
            if(is_array($pageSize)) {
                foreach($pageSize as $key => $value) {
                    $queryParams[$key] = $value;
                }
            }
            else {
                $queryParams['page_size'] = $pageSize;
            }
        }




        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            '',
            $multipart
        );

        // for model (json/xml)
        if ($formParams !== []) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }

                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($this->headerSelector->isJsonMime($headers['Content-Type'])) {
                $httpBody = json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();

        $uri = $this->createUri($operationHost, $resourcePath, $queryParams);

        return $this->createRequest('GET', $uri, $headers, $httpBody);
    }

    /**
     * Operation scPublicV3ScpPatchReturnsCancel
     *
     * Request cancellation of a return
     *
     * @param  int $id The internal Sendcloud id of this return (required)
     *
     * @throws \Toppy\Sendcloud\V3\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Toppy\Sendcloud\V3\Model\ScPublicV3ScpPatchReturnsCancel202Response|\Toppy\Sendcloud\V3\Model\ScPublicV3ScpPatchReturnsCancel409Response
     */
    public function scPublicV3ScpPatchReturnsCancel($id)
    {
        [$response] = $this->scPublicV3ScpPatchReturnsCancelWithHttpInfo($id);
        return $response;
    }

    /**
     * Operation scPublicV3ScpPatchReturnsCancelWithHttpInfo
     *
     * Request cancellation of a return
     *
     * @param  int $id The internal Sendcloud id of this return (required)
     *
     * @throws \Toppy\Sendcloud\V3\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Toppy\Sendcloud\V3\Model\ScPublicV3ScpPatchReturnsCancel202Response|\Toppy\Sendcloud\V3\Model\ScPublicV3ScpPatchReturnsCancel409Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function scPublicV3ScpPatchReturnsCancelWithHttpInfo($id)
    {
        $request = $this->scPublicV3ScpPatchReturnsCancelRequest($id);

        try {
            try {
                $response = $this->httpClient->sendRequest($request);
            } catch (HttpException $e) {
                $response = $e->getResponse();
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $response->getStatusCode(),
                        (string) $request->getUri()
                    ),
                    $request,
                    $response,
                    $e
                );
            } catch (ClientExceptionInterface $e) {
                throw new ApiException(
                    sprintf('[%d] %s', $e->getCode(), $e->getMessage()),
                    $request,
                    null,
                    $e
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 202:
                    return $this->handleResponseWithDataType(
                        \Toppy\Sendcloud\V3\Model\ScPublicV3ScpPatchReturnsCancel202Response::class,
                        $request,
                        $response,
                    );
                case 409:
                    return $this->handleResponseWithDataType(
                        \Toppy\Sendcloud\V3\Model\ScPublicV3ScpPatchReturnsCancel409Response::class,
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $request,
                    $response
                );
            }

            return $this->handleResponseWithDataType(
                \Toppy\Sendcloud\V3\Model\ScPublicV3ScpPatchReturnsCancel202Response::class,
                $request,
                $response,
            );
        } catch (ApiException $apiException) {
            switch ($apiException->getCode()) {
                case 202:
                    $data = ObjectSerializer::deserialize(
                        $apiException->getResponseBody(),
                        \Toppy\Sendcloud\V3\Model\ScPublicV3ScpPatchReturnsCancel202Response::class,
                        $apiException->getResponseHeaders()
                    );
                    $apiException->setResponseObject($data);
                    throw $apiException;
                case 409:
                    $data = ObjectSerializer::deserialize(
                        $apiException->getResponseBody(),
                        \Toppy\Sendcloud\V3\Model\ScPublicV3ScpPatchReturnsCancel409Response::class,
                        $apiException->getResponseHeaders()
                    );
                    $apiException->setResponseObject($data);
                    throw $apiException;
            }
        

            throw $apiException;
        }
    }

    /**
     * Operation scPublicV3ScpPatchReturnsCancelAsync
     *
     * Request cancellation of a return
     *
     * @param  int $id The internal Sendcloud id of this return (required)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function scPublicV3ScpPatchReturnsCancelAsync($id)
    {
        return $this->scPublicV3ScpPatchReturnsCancelAsyncWithHttpInfo($id)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation scPublicV3ScpPatchReturnsCancelAsyncWithHttpInfo
     *
     * Request cancellation of a return
     *
     * @param  int $id The internal Sendcloud id of this return (required)
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function scPublicV3ScpPatchReturnsCancelAsyncWithHttpInfo($id)
    {
        $returnType = \Toppy\Sendcloud\V3\Model\ScPublicV3ScpPatchReturnsCancel202Response::class;
        $request = $this->scPublicV3ScpPatchReturnsCancelRequest($id);

        return $this->httpAsyncClient->sendAsyncRequest($request)
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function (HttpException $httpException) {
                    $response = $httpException->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $httpException->getRequest()->getUri()
                        ),
                        $httpException->getRequest(),
                        $httpException->getResponse(),
                        $httpException
                    );
                }
            );
    }

    /**
     * Create request for operation 'scPublicV3ScpPatchReturnsCancel'
     *
     * @param  int $id The internal Sendcloud id of this return (required)
     *
     * @throws \InvalidArgumentException
     * @return RequestInterface
     */
    public function scPublicV3ScpPatchReturnsCancelRequest($id)
    {
        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && $id === [])) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling scPublicV3ScpPatchReturnsCancel'
            );
        }

        $resourcePath = '/returns/{id}/cancel';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = null;
        $multipart = false;



        // path params
        $resourcePath = str_replace(
            '{id}',
            ObjectSerializer::toPathValue($id),
            $resourcePath
        );


        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            '',
            $multipart
        );

        // for model (json/xml)
        if ($formParams !== []) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }

                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($this->headerSelector->isJsonMime($headers['Content-Type'])) {
                $httpBody = json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();

        $uri = $this->createUri($operationHost, $resourcePath, $queryParams);

        return $this->createRequest('PATCH', $uri, $headers, $httpBody);
    }

    /**
     * Operation scPublicV3ScpPostReturnsCreateNewReturn
     *
     * Create a return
     *
     *
     * @throws \Toppy\Sendcloud\V3\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Toppy\Sendcloud\V3\Model\ScPublicV3ScpPostReturnsCreateNewReturn201Response|\Toppy\Sendcloud\V3\Model\Errors
     */
    public function scPublicV3ScpPostReturnsCreateNewReturn()
    {
        [$response] = $this->scPublicV3ScpPostReturnsCreateNewReturnWithHttpInfo();
        return $response;
    }

    /**
     * Operation scPublicV3ScpPostReturnsCreateNewReturnWithHttpInfo
     *
     * Create a return
     *
     *
     * @throws \Toppy\Sendcloud\V3\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Toppy\Sendcloud\V3\Model\ScPublicV3ScpPostReturnsCreateNewReturn201Response|\Toppy\Sendcloud\V3\Model\Errors, HTTP status code, HTTP response headers (array of strings)
     */
    public function scPublicV3ScpPostReturnsCreateNewReturnWithHttpInfo()
    {
        $request = $this->scPublicV3ScpPostReturnsCreateNewReturnRequest();

        try {
            try {
                $response = $this->httpClient->sendRequest($request);
            } catch (HttpException $e) {
                $response = $e->getResponse();
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $response->getStatusCode(),
                        (string) $request->getUri()
                    ),
                    $request,
                    $response,
                    $e
                );
            } catch (ClientExceptionInterface $e) {
                throw new ApiException(
                    sprintf('[%d] %s', $e->getCode(), $e->getMessage()),
                    $request,
                    null,
                    $e
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 201:
                    return $this->handleResponseWithDataType(
                        \Toppy\Sendcloud\V3\Model\ScPublicV3ScpPostReturnsCreateNewReturn201Response::class,
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        \Toppy\Sendcloud\V3\Model\Errors::class,
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $request,
                    $response
                );
            }

            return $this->handleResponseWithDataType(
                \Toppy\Sendcloud\V3\Model\ScPublicV3ScpPostReturnsCreateNewReturn201Response::class,
                $request,
                $response,
            );
        } catch (ApiException $apiException) {
            switch ($apiException->getCode()) {
                case 201:
                    $data = ObjectSerializer::deserialize(
                        $apiException->getResponseBody(),
                        \Toppy\Sendcloud\V3\Model\ScPublicV3ScpPostReturnsCreateNewReturn201Response::class,
                        $apiException->getResponseHeaders()
                    );
                    $apiException->setResponseObject($data);
                    throw $apiException;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $apiException->getResponseBody(),
                        \Toppy\Sendcloud\V3\Model\Errors::class,
                        $apiException->getResponseHeaders()
                    );
                    $apiException->setResponseObject($data);
                    throw $apiException;
            }
        

            throw $apiException;
        }
    }

    /**
     * Operation scPublicV3ScpPostReturnsCreateNewReturnAsync
     *
     * Create a return
     *
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function scPublicV3ScpPostReturnsCreateNewReturnAsync()
    {
        return $this->scPublicV3ScpPostReturnsCreateNewReturnAsyncWithHttpInfo()
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation scPublicV3ScpPostReturnsCreateNewReturnAsyncWithHttpInfo
     *
     * Create a return
     *
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function scPublicV3ScpPostReturnsCreateNewReturnAsyncWithHttpInfo()
    {
        $returnType = \Toppy\Sendcloud\V3\Model\ScPublicV3ScpPostReturnsCreateNewReturn201Response::class;
        $request = $this->scPublicV3ScpPostReturnsCreateNewReturnRequest();

        return $this->httpAsyncClient->sendAsyncRequest($request)
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function (HttpException $httpException) {
                    $response = $httpException->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $httpException->getRequest()->getUri()
                        ),
                        $httpException->getRequest(),
                        $httpException->getResponse(),
                        $httpException
                    );
                }
            );
    }

    /**
     * Create request for operation 'scPublicV3ScpPostReturnsCreateNewReturn'
     *
     *
     * @throws \InvalidArgumentException
     * @return RequestInterface
     */
    public function scPublicV3ScpPostReturnsCreateNewReturnRequest()
    {

        $resourcePath = '/returns';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = null;
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            '',
            $multipart
        );

        // for model (json/xml)
        if ($formParams !== []) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }

                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($this->headerSelector->isJsonMime($headers['Content-Type'])) {
                $httpBody = json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();

        $uri = $this->createUri($operationHost, $resourcePath, $queryParams);

        return $this->createRequest('POST', $uri, $headers, $httpBody);
    }

    /**
     * Operation scPublicV3ScpPostReturnsCreateNewReturnSynchronously
     *
     * Create a return synchronously
     *
     *
     * @throws \Toppy\Sendcloud\V3\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Toppy\Sendcloud\V3\Model\ScPublicV3ScpPostReturnsCreateNewReturn201Response
     */
    public function scPublicV3ScpPostReturnsCreateNewReturnSynchronously()
    {
        [$response] = $this->scPublicV3ScpPostReturnsCreateNewReturnSynchronouslyWithHttpInfo();
        return $response;
    }

    /**
     * Operation scPublicV3ScpPostReturnsCreateNewReturnSynchronouslyWithHttpInfo
     *
     * Create a return synchronously
     *
     *
     * @throws \Toppy\Sendcloud\V3\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Toppy\Sendcloud\V3\Model\ScPublicV3ScpPostReturnsCreateNewReturn201Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function scPublicV3ScpPostReturnsCreateNewReturnSynchronouslyWithHttpInfo()
    {
        $request = $this->scPublicV3ScpPostReturnsCreateNewReturnSynchronouslyRequest();

        try {
            try {
                $response = $this->httpClient->sendRequest($request);
            } catch (HttpException $e) {
                $response = $e->getResponse();
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $response->getStatusCode(),
                        (string) $request->getUri()
                    ),
                    $request,
                    $response,
                    $e
                );
            } catch (ClientExceptionInterface $e) {
                throw new ApiException(
                    sprintf('[%d] %s', $e->getCode(), $e->getMessage()),
                    $request,
                    null,
                    $e
                );
            }

            $statusCode = $response->getStatusCode();


            if ($statusCode === 201) {
                return $this->handleResponseWithDataType(
                    \Toppy\Sendcloud\V3\Model\ScPublicV3ScpPostReturnsCreateNewReturn201Response::class,
                    $request,
                    $response,
                );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $request,
                    $response
                );
            }

            return $this->handleResponseWithDataType(
                \Toppy\Sendcloud\V3\Model\ScPublicV3ScpPostReturnsCreateNewReturn201Response::class,
                $request,
                $response,
            );
        } catch (ApiException $apiException) {
            if ($apiException->getCode() === 201) {
                $data = ObjectSerializer::deserialize(
                    $apiException->getResponseBody(),
                    \Toppy\Sendcloud\V3\Model\ScPublicV3ScpPostReturnsCreateNewReturn201Response::class,
                    $apiException->getResponseHeaders()
                );
                $apiException->setResponseObject($data);
                throw $apiException;
            }
        

            throw $apiException;
        }
    }

    /**
     * Operation scPublicV3ScpPostReturnsCreateNewReturnSynchronouslyAsync
     *
     * Create a return synchronously
     *
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function scPublicV3ScpPostReturnsCreateNewReturnSynchronouslyAsync()
    {
        return $this->scPublicV3ScpPostReturnsCreateNewReturnSynchronouslyAsyncWithHttpInfo()
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation scPublicV3ScpPostReturnsCreateNewReturnSynchronouslyAsyncWithHttpInfo
     *
     * Create a return synchronously
     *
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function scPublicV3ScpPostReturnsCreateNewReturnSynchronouslyAsyncWithHttpInfo()
    {
        $returnType = \Toppy\Sendcloud\V3\Model\ScPublicV3ScpPostReturnsCreateNewReturn201Response::class;
        $request = $this->scPublicV3ScpPostReturnsCreateNewReturnSynchronouslyRequest();

        return $this->httpAsyncClient->sendAsyncRequest($request)
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function (HttpException $httpException) {
                    $response = $httpException->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $httpException->getRequest()->getUri()
                        ),
                        $httpException->getRequest(),
                        $httpException->getResponse(),
                        $httpException
                    );
                }
            );
    }

    /**
     * Create request for operation 'scPublicV3ScpPostReturnsCreateNewReturnSynchronously'
     *
     *
     * @throws \InvalidArgumentException
     * @return RequestInterface
     */
    public function scPublicV3ScpPostReturnsCreateNewReturnSynchronouslyRequest()
    {

        $resourcePath = '/returns/announce-synchronously';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = null;
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            '',
            $multipart
        );

        // for model (json/xml)
        if ($formParams !== []) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }

                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($this->headerSelector->isJsonMime($headers['Content-Type'])) {
                $httpBody = json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();

        $uri = $this->createUri($operationHost, $resourcePath, $queryParams);

        return $this->createRequest('POST', $uri, $headers, $httpBody);
    }

    /**
     * Operation scPublicV3ScpPostReturnsValidate
     *
     * Validate a return
     *
     *
     * @throws \Toppy\Sendcloud\V3\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Toppy\Sendcloud\V3\Model\ReturnValidation|\Toppy\Sendcloud\V3\Model\Errors
     */
    public function scPublicV3ScpPostReturnsValidate()
    {
        [$response] = $this->scPublicV3ScpPostReturnsValidateWithHttpInfo();
        return $response;
    }

    /**
     * Operation scPublicV3ScpPostReturnsValidateWithHttpInfo
     *
     * Validate a return
     *
     *
     * @throws \Toppy\Sendcloud\V3\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Toppy\Sendcloud\V3\Model\ReturnValidation|\Toppy\Sendcloud\V3\Model\Errors, HTTP status code, HTTP response headers (array of strings)
     */
    public function scPublicV3ScpPostReturnsValidateWithHttpInfo()
    {
        $request = $this->scPublicV3ScpPostReturnsValidateRequest();

        try {
            try {
                $response = $this->httpClient->sendRequest($request);
            } catch (HttpException $e) {
                $response = $e->getResponse();
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $response->getStatusCode(),
                        (string) $request->getUri()
                    ),
                    $request,
                    $response,
                    $e
                );
            } catch (ClientExceptionInterface $e) {
                throw new ApiException(
                    sprintf('[%d] %s', $e->getCode(), $e->getMessage()),
                    $request,
                    null,
                    $e
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        \Toppy\Sendcloud\V3\Model\ReturnValidation::class,
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        \Toppy\Sendcloud\V3\Model\Errors::class,
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $request,
                    $response
                );
            }

            return $this->handleResponseWithDataType(
                \Toppy\Sendcloud\V3\Model\ReturnValidation::class,
                $request,
                $response,
            );
        } catch (ApiException $apiException) {
            switch ($apiException->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $apiException->getResponseBody(),
                        \Toppy\Sendcloud\V3\Model\ReturnValidation::class,
                        $apiException->getResponseHeaders()
                    );
                    $apiException->setResponseObject($data);
                    throw $apiException;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $apiException->getResponseBody(),
                        \Toppy\Sendcloud\V3\Model\Errors::class,
                        $apiException->getResponseHeaders()
                    );
                    $apiException->setResponseObject($data);
                    throw $apiException;
            }
        

            throw $apiException;
        }
    }

    /**
     * Operation scPublicV3ScpPostReturnsValidateAsync
     *
     * Validate a return
     *
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function scPublicV3ScpPostReturnsValidateAsync()
    {
        return $this->scPublicV3ScpPostReturnsValidateAsyncWithHttpInfo()
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation scPublicV3ScpPostReturnsValidateAsyncWithHttpInfo
     *
     * Validate a return
     *
     *
     * @throws \InvalidArgumentException
     * @return Promise
     */
    public function scPublicV3ScpPostReturnsValidateAsyncWithHttpInfo()
    {
        $returnType = \Toppy\Sendcloud\V3\Model\ReturnValidation::class;
        $request = $this->scPublicV3ScpPostReturnsValidateRequest();

        return $this->httpAsyncClient->sendAsyncRequest($request)
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function (HttpException $httpException) {
                    $response = $httpException->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $httpException->getRequest()->getUri()
                        ),
                        $httpException->getRequest(),
                        $httpException->getResponse(),
                        $httpException
                    );
                }
            );
    }

    /**
     * Create request for operation 'scPublicV3ScpPostReturnsValidate'
     *
     *
     * @throws \InvalidArgumentException
     * @return RequestInterface
     */
    public function scPublicV3ScpPostReturnsValidateRequest()
    {

        $resourcePath = '/returns/validate';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = null;
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json'],
            '',
            $multipart
        );

        // for model (json/xml)
        if ($formParams !== []) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }

                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($this->headerSelector->isJsonMime($headers['Content-Type'])) {
                $httpBody = json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires HTTP basic authentication
        if (!empty($this->config->getUsername()) || !(empty($this->config->getPassword()))) {
            $headers['Authorization'] = 'Basic ' . base64_encode($this->config->getUsername() . ":" . $this->config->getPassword());
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();

        $uri = $this->createUri($operationHost, $resourcePath, $queryParams);

        return $this->createRequest('POST', $uri, $headers, $httpBody);
    }


    /**
     * @param string|UriInterface $uri
     * @param string[] $headers
     * @param string|StreamInterface|null $body
     *
     */
    protected function createRequest(string $method, $uri, array $headers = [], $body = null): RequestInterface
    {
        if ($this->requestFactory instanceof RequestFactory) {
            return $this->requestFactory->createRequest(
                $method,
                $uri,
                $headers,
                $body
            );
        }

        if (is_string($body) && '' !== $body && null === $this->streamFactory) {
            throw new \RuntimeException('Cannot create request: A stream factory is required to create a request with a non-empty string body.');
        }

        $request = $this->requestFactory->createRequest($method, $uri);

        foreach ($headers as $key => $value) {
            $request = $request->withHeader($key, $value);
        }

        if (null !== $body && '' !== $body) {
            return $request->withBody(
                is_string($body) ? $this->streamFactory->createStream($body) : $body
            );
        }

        return $request;
    }

    /**
     * @param array<string, string>|array<string, float> $queryParams
     */
    private function createUri(
        string $operationHost,
        string $resourcePath,
        array $queryParams
    ): UriInterface {
        $parsedUrl = parse_url($operationHost);

        $host = $parsedUrl['host'] ?? null;
        $scheme = $parsedUrl['scheme'] ?? null;
        $basePath = $parsedUrl['path'] ?? null;
        $port = $parsedUrl['port'] ?? null;
        $user = $parsedUrl['user'] ?? null;
        $password = $parsedUrl['pass'] ?? null;

        $uri = $this->uriFactory->createUri($basePath . $resourcePath)
            ->withHost($host)
            ->withScheme($scheme)
            ->withPort($port)
            ->withQuery(ObjectSerializer::buildQuery($queryParams));

        if ($user) {
            return $uri->withUserInfo($user, $password);
        }

        return $uri;
    }

    /**
     * @return array<int, object|int|mixed[]|null>
     */
    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
			$request,
                        $response,
                        $exception
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }
}
