<?php
/**
 * DynamicCheckoutDeliveryOptionCheckoutIdentifierTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Toppy\Sendcloud\V3
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Sendcloud Public REST API
 *
 * Complete Sendcloud API v3 specification - merged from official sendcloud.dev documentation
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: contact@sendcloud.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.18.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Toppy\Sendcloud\V3\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * DynamicCheckoutDeliveryOptionCheckoutIdentifierTest Class Doc Comment
 *
 * @category    Class
 * @description An object containing the type and value of the checkout identifier.  The type is determined by the &#x60;checkout_identifier_type&#x60; query parameter, and the value depends on the specified type. For example, if &#x60;shipping_option_code&#x60; is used, the value contains the shipping option code needed to [create a shipment](/api/v3/shipments/create-and-announce-a-shipment-asynchronously) with the Shipments API.
 * @package     Toppy\Sendcloud\V3
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class DynamicCheckoutDeliveryOptionCheckoutIdentifierTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "DynamicCheckoutDeliveryOptionCheckoutIdentifier"
     */
    public function testDynamicCheckoutDeliveryOptionCheckoutIdentifier()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "value"
     */
    public function testPropertyValue()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
