<?php
/**
 * ParcelTrackingShipWithTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Toppy\Sendcloud\V3
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Sendcloud Public REST API
 *
 * Complete Sendcloud API v3 specification - merged from official sendcloud.dev documentation
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: contact@sendcloud.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.18.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Toppy\Sendcloud\V3\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * ParcelTrackingShipWithTest Class Doc Comment
 *
 * @category    Class
 * @description The ship with object can be used to define how you would like to send your shipment.  You can use one of the following types: - &#x60;shipping_option_code&#x60;: Use a shipping option code to specify the carrier and shipping functionalities. The &#x60;shipping_option_code&#x60; property is required, and &#x60;contract_id&#x60; is optional. - &#x60;contract&#x60;: Use a contract to specify which carrier contract to use. The &#x60;contract_id&#x60; property is required.
 * @package     Toppy\Sendcloud\V3
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ParcelTrackingShipWithTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ParcelTrackingShipWith"
     */
    public function testParcelTrackingShipWith()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "properties"
     */
    public function testPropertyProperties()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
