<?php
/**
 * ScPublicV3DsfPostRequestedDataRequestSalesDataInnerTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Toppy\Sendcloud
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Sendcloud Public REST API
 *
 * Complete Sendcloud API v3 specification - merged from official Stoplight documentation bundles
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: contact@sendcloud.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.18.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Toppy\Sendcloud\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * ScPublicV3DsfPostRequestedDataRequestSalesDataInnerTest Class Doc Comment
 *
 * @category    Class
 * @description ScPublicV3DsfPostRequestedDataRequestSalesDataInner
 * @package     Toppy\Sendcloud
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ScPublicV3DsfPostRequestedDataRequestSalesDataInnerTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ScPublicV3DsfPostRequestedDataRequestSalesDataInner"
     */
    public function testScPublicV3DsfPostRequestedDataRequestSalesDataInner()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "productDescription"
     */
    public function testPropertyProductDescription()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "quantity"
     */
    public function testPropertyQuantity()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "sellingPrice"
     */
    public function testPropertySellingPrice()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "currency"
     */
    public function testPropertyCurrency()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "taxRate"
     */
    public function testPropertyTaxRate()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
