<?php
/**
 * ScPublicV3DsfPostTicketsDelayRequestTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Toppy\Sendcloud\V3
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Sendcloud Public REST API
 *
 * Complete Sendcloud API v3 specification - merged from official sendcloud.dev documentation
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: contact@sendcloud.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.18.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Toppy\Sendcloud\V3\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * ScPublicV3DsfPostTicketsDelayRequestTest Class Doc Comment
 *
 * @category    Class
 * @description ScPublicV3DsfPostTicketsDelayRequest
 * @package     Toppy\Sendcloud\V3
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ScPublicV3DsfPostTicketsDelayRequestTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ScPublicV3DsfPostTicketsDelayRequest"
     */
    public function testScPublicV3DsfPostTicketsDelayRequest()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "trackingNumber"
     */
    public function testPropertyTrackingNumber()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "contentsSalesPrice"
     */
    public function testPropertyContentsSalesPrice()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "contentsPurchasePrice"
     */
    public function testPropertyContentsPurchasePrice()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "contentsDescription"
     */
    public function testPropertyContentsDescription()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "parcelExteriorDescription"
     */
    public function testPropertyParcelExteriorDescription()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "salesInvoice"
     */
    public function testPropertySalesInvoice()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "purchaseInvoice"
     */
    public function testPropertyPurchaseInvoice()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
