<?php
/**
 * ShippingOptionCodePropertiesTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Toppy\Sendcloud
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Sendcloud Public REST API
 *
 * Complete Sendcloud API v3 specification - merged from official Stoplight documentation bundles
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: contact@sendcloud.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.18.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Toppy\Sendcloud\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * ShippingOptionCodePropertiesTest Class Doc Comment
 *
 * @category    Class
 * @description Contains the required properties to be sent when API client informs the shipping method and carrier to be used
 * @package     Toppy\Sendcloud
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ShippingOptionCodePropertiesTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ShippingOptionCodeProperties"
     */
    public function testShippingOptionCodeProperties()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "shippingOptionCode"
     */
    public function testPropertyShippingOptionCode()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "contractId"
     */
    public function testPropertyContractId()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
