<?php
/**
 * CreateTicketApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  Toppy\Sendcloud\V3
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Sendcloud Public REST API
 *
 * Complete Sendcloud API v3 specification - merged from official sendcloud.dev documentation
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: contact@sendcloud.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.18.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Toppy\Sendcloud\V3\Test\Api;

use \Toppy\Sendcloud\V3\Configuration;
use \Toppy\Sendcloud\V3\ApiException;
use \Toppy\Sendcloud\V3\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * CreateTicketApiTest Class Doc Comment
 *
 * @category Class
 * @package  Toppy\Sendcloud\V3
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class CreateTicketApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for scPublicV3DsfPostTicketsAddressChange
     *
     * Create a ticket for an address change.
     *
     */
    public function testScPublicV3DsfPostTicketsAddressChange()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for scPublicV3DsfPostTicketsDamage
     *
     * Create a ticket for a damaged parcel.
     *
     */
    public function testScPublicV3DsfPostTicketsDamage()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for scPublicV3DsfPostTicketsDelay
     *
     * Create a ticket for a delayed parcel.
     *
     */
    public function testScPublicV3DsfPostTicketsDelay()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for scPublicV3DsfPostTicketsDeliveredButNotReceived
     *
     * Create a ticket for a delivered but not received parcel.
     *
     */
    public function testScPublicV3DsfPostTicketsDeliveredButNotReceived()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for scPublicV3DsfPostTicketsLost
     *
     * Create a ticket for a lost parcel.
     *
     */
    public function testScPublicV3DsfPostTicketsLost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for scPublicV3DsfPostTicketsUnjustReturn
     *
     * Create a ticket for an unjustly returned parcel.
     *
     */
    public function testScPublicV3DsfPostTicketsUnjustReturn()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
